# Generated by Django 5.2.15 on 2026-07-12 23:32
"""Governed procedure family tables (ME2)."""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import InvenTree.models


class Migration(migrations.Migration):
    """Add procedure, revision, step, and resource models."""


    dependencies = [
        ("assets", "0003_assetmachine_customer_idx"),
        ("company", "0080_company_tags"),
        ("part", "0152_alter_partpricing_currency"),
        ("repair", "0004_seed_safety_gate_templates"),
        ("tasks", "0003_work_order_schema_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcedureRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "work_order_type",
                    models.CharField(
                        choices=[
                            ("corrective", "Corrective"),
                            ("preventive", "Preventive"),
                            ("inspection", "Inspection"),
                            ("calibration", "Calibration"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_summary", models.TextField(blank=True)),
                (
                    "default_estimated_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("review_due_at", models.DateTimeField(blank=True, null=True)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("content_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="tasks.procedure",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcedureResourceRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("part", "Part"),
                            ("consumable", "Consumable"),
                            ("tool", "Tool"),
                            ("safety", "Safety Equipment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=15)),
                (
                    "fulfillment_mode",
                    models.CharField(
                        choices=[
                            ("reserve_consume", "Reserve and Consume"),
                            ("checkout_return", "Checkout and Return"),
                            ("verify_only", "Verify Only"),
                        ],
                        max_length=24,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                (
                    "substitution_policy",
                    models.CharField(
                        choices=[
                            ("none", "No Substitution"),
                            ("approved_only", "Approved Alternates Only"),
                            ("supervisor", "Supervisor Approval"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("requires_scan", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="part.part"
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_requirements",
                        to="tasks.procedurerevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcedureFieldDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_path", models.CharField(max_length=255)),
                ("origin", models.CharField(max_length=20)),
                ("proposal", models.JSONField(default=dict)),
                ("decision", models.CharField(max_length=16)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_decisions",
                        to="tasks.procedurerevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcedureApplicability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("location_pattern", models.CharField(blank=True, max_length=255)),
                ("required_tags", models.JSONField(blank=True, default=list)),
                ("predicate", models.JSONField(blank=True, default=dict)),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assetmachine",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicability_rules",
                        to="tasks.procedurerevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="procedure",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tasks.procedurerevision",
            ),
        ),
        migrations.CreateModel(
            name="ProcedureRevisionSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_snapshot", models.JSONField()),
                ("source_hash", models.CharField(max_length=64)),
                ("captured_at", models.DateTimeField()),
                (
                    "captured_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maintenance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assetmaintenancerecord",
                    ),
                ),
                (
                    "packet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="repair.repairpacket",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="tasks.procedurerevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcedureStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("instruction", "Instruction"),
                            ("measurement", "Measurement"),
                            ("inspection", "Inspection"),
                            ("safety", "Safety Reference"),
                            ("hold_point", "Hold Point"),
                            ("verification", "Verification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("instruction", models.TextField()),
                ("required", models.BooleanField(default=True)),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("required_permission", models.CharField(blank=True, max_length=100)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("number", "Number"),
                            ("boolean", "Pass / Fail"),
                            ("choice", "Choice"),
                            ("text", "Text"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=64)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("allowed_values", models.JSONField(blank=True, default=list)),
                ("evidence_policy", models.JSONField(blank=True, default=dict)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="tasks.procedurerevision",
                    ),
                ),
                (
                    "safety_gate_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_steps",
                        to="repair.safetygatetemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrderProcedureApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("primary", models.BooleanField(default=True)),
                ("snapshot", models.JSONField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("policy_version", models.PositiveSmallIntegerField(default=1)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("drift_status", models.CharField(default="current", max_length=20)),
                (
                    "applied_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasks.procedurerevision",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_applications",
                        to="tasks.kanbancard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrderStepExecution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_key", models.UUIDField()),
                ("sequence", models.PositiveIntegerField()),
                ("step_snapshot", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("not_applicable", "Not Applicable"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
                ("passed", models.BooleanField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("disposition_reason", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="tasks.workorderprocedureapplication",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(InvenTree.models.InvenTreeAttachmentMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="procedurerevision",
            constraint=models.UniqueConstraint(
                fields=("procedure", "revision"), name="tasks_procedure_revision_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gt", 0)),
                name="tasks_procedure_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_version__gt", 0)),
                name="tasks_procedure_content_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurerevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("procedure",),
                name="tasks_procedure_one_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "published"), _negated=True),
                    models.Q(
                        ("published_by__isnull", False), ("published_at__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="tasks_procedure_published_metadata",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureresourcerequirement",
            constraint=models.UniqueConstraint(
                fields=("revision", "key"), name="tasks_resource_revision_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureresourcerequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="tasks_resource_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedureresourcerequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="tasks_resource_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedure",
            constraint=models.UniqueConstraint(
                fields=("customer", "code"), name="tasks_procedure_scope_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurestep",
            constraint=models.UniqueConstraint(
                fields=("revision", "sequence"),
                name="tasks_step_revision_sequence_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurestep",
            constraint=models.UniqueConstraint(
                fields=("revision", "key"), name="tasks_step_revision_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="procedurestep",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="tasks_step_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderprocedureapplication",
            constraint=models.UniqueConstraint(
                fields=("work_order", "idempotency_key"),
                name="tasks_application_work_order_idem_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderprocedureapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("primary", True)),
                fields=("work_order",),
                name="tasks_application_one_primary",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderstepexecution",
            constraint=models.UniqueConstraint(
                fields=("application", "step_key"),
                name="tasks_execution_application_step_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderstepexecution",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="tasks_execution_version_positive",
            ),
        ),
    ]
