# Generated by Django 5.2.15 on 2026-07-13 04:37
"""Real job-kit stock allocations (ME5)."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the JobKitAllocation model."""


    dependencies = [
        ("stock", "0123_remove_stockitem_review_needed"),
        ("tasks", "0005_jobkit_planning_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobKitAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=5, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("staged", "Staged"),
                            ("issued", "Issued"),
                            ("consumed", "Consumed"),
                            ("returned", "Returned"),
                            ("released", "Released"),
                            ("exception", "Exception"),
                        ],
                        db_index=True,
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("source_location_snapshot", models.JSONField(default=dict)),
                ("scan_proof", models.JSONField(blank=True, default=dict)),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("staged_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("disposed_at", models.DateTimeField(blank=True, null=True)),
                ("stock_tracking_id", models.IntegerField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="tasks.jobkitline",
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_kit_allocations",
                        to="stock.stockitem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="tasks_jobkitallocation_qty_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["reserved", "staged", "issued"])
                        ),
                        fields=("line", "stock_item"),
                        name="tasks_jobkitallocation_active_line_stock_uniq",
                    ),
                ],
            },
        ),
    ]
