# Generated by Django 5.2.15 on 2026-07-16 04:44
"""Closeout Automation substrate tables (Feature #15)."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Additive capture/proposal/reconciliation/effect/amendment models."""

    dependencies = [
        ("approvals", "0004_alter_approval_action_type"),
        ("common", "0047_merge_20260712_2258"),
        ("part", "0152_alter_partpricing_currency"),
        ("stock", "0123_remove_stockitem_review_needed"),
        ("tasks", "0007_jobkitsubstitution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloseoutAmendment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changes", models.JSONField()),
                ("base_content_hash", models.CharField(max_length=64)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("effective_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "effective_snapshot_hash",
                    models.CharField(blank=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="approvals.approval",
                    ),
                ),
                (
                    "closeout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amendments",
                        to="tasks.workordercloseout",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloseoutCapture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("extracting", "Extracting"),
                            ("proposed", "Proposed"),
                            ("reviewed", "Reviewed"),
                            ("consumed", "Consumed by Completion"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("typed", "Typed"),
                            ("voice", "Reviewed Voice Transcript"),
                        ],
                        default="typed",
                        max_length=16,
                    ),
                ),
                (
                    "transcript_reference",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_closeout",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_capture",
                        to="tasks.workordercloseout",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closeout_captures",
                        to="tasks.kanbancard",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("capture_closeout", "Can capture closeout narratives"),
                    ("review_closeout", "Can review closeout proposals"),
                    ("reconcile_closeout_parts", "Can reconcile closeout part usage"),
                    ("verify_closeout", "Can verify completed closeouts"),
                    ("amend_closeout", "Can amend completed closeouts"),
                    ("view_closeout_audit", "Can view closeout audit surfaces"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CloseoutCaptureRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("narrative", models.TextField()),
                ("source_content_hash", models.CharField(max_length=64)),
                ("work_order_version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="tasks.closeoutcapture",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="tasks.closeoutcapturerevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="closeoutcapture",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tasks.closeoutcapturerevision",
            ),
        ),
        migrations.CreateModel(
            name="CloseoutEffect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effect_type", models.CharField(db_index=True, max_length=40)),
                ("effect_key", models.CharField(max_length=128, unique=True)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("leased", "Leased"),
                            ("dispatching", "Dispatching"),
                            ("retryable", "Retryable"),
                            ("outcome_unknown", "Outcome Unknown"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("lease_owner", models.CharField(blank=True, max_length=128)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("reconciliation_due_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("result_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closeout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="effects",
                        to="tasks.workordercloseout",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloseoutLearningDraft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "draft_type",
                    models.CharField(default="problem_solution", max_length=40),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(db_index=True, default="draft", max_length=16),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closeout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_drafts",
                        to="tasks.workordercloseout",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloseoutPartUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "issued_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "used_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("consumed", "Consumed"),
                            ("returned", "Returned Unused"),
                            ("scrapped", "Scrapped"),
                            ("spare_installed", "Installed as Spare"),
                            ("serialized_manual", "Serialized - Manual Handling"),
                            ("correction", "Quantity Correction"),
                            ("dismissed", "Candidate Dismissed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("variance_reason", models.TextField(blank=True)),
                ("stock_tracking_id", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(default="kit", max_length=16)),
                ("candidate_text", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reconciled", "Reconciled"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasks.jobkitallocation",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="part.part",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.stockitem",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closeout_part_usage",
                        to="tasks.kanbancard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloseoutProposal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("extractor", models.CharField(max_length=64)),
                ("model_provenance", models.JSONField(blank=True, default=dict)),
                ("fields", models.JSONField()),
                ("part_candidates", models.JSONField(blank=True, default=list)),
                ("reading_candidates", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("reviewed", "Reviewed"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capture_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="tasks.closeoutcapturerevision",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tasks.closeoutproposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloseoutFieldDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_path", models.CharField(max_length=128)),
                ("origin", models.CharField(max_length=16)),
                ("decision", models.CharField(max_length=16)),
                ("final_value", models.JSONField(blank=True, default=dict)),
                ("decided_at", models.DateTimeField()),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="tasks.closeoutproposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloseoutReading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=128)),
                ("phase", models.CharField(default="after", max_length=8)),
                ("raw_text", models.CharField(max_length=64)),
                ("source_spans", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=32)),
                (
                    "expected_min",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "expected_max",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("normalization_rule_version", models.CharField(max_length=32)),
                (
                    "verification_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("dispositioned", "Dispositioned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("disposition_reason", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tasks.workorderstepexecution",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closeout_readings",
                        to="tasks.kanbancard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CloseoutReadingEvidence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.attachment",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="tasks.closeoutreading",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="closeoutcapturerevision",
            constraint=models.UniqueConstraint(
                fields=("capture", "revision"), name="tasks_closeout_cap_rev_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="closeoutcapture",
            index=models.Index(
                fields=["work_order", "status"], name="tasks_closeout_cap_wo_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="closeoutcapture",
            constraint=models.UniqueConstraint(
                fields=("work_order", "transcript_reference"),
                name="tasks_closeout_voice_ref_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="closeoutcapture",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_type", "voice"), _negated=True),
                    models.Q(
                        ("transcript_reference__isnull", False),
                        models.Q(("transcript_reference", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tasks_closeout_voice_ref_req",
            ),
        ),
        migrations.AddIndex(
            model_name="closeouteffect",
            index=models.Index(
                fields=["closeout", "effect_type"], name="tasks_closeout_eff_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="closeoutlearningdraft",
            constraint=models.UniqueConstraint(
                fields=("closeout", "draft_type"), name="tasks_closeout_draft_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="closeoutpartusage",
            index=models.Index(
                fields=["work_order", "state"], name="tasks_closeout_usage_wo_state"
            ),
        ),
        migrations.AddConstraint(
            model_name="closeoutpartusage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("allocation__isnull", False)),
                fields=("work_order", "allocation"),
                name="tasks_closeout_usage_alloc_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="closeoutproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "superseded"), _negated=True),
                fields=("capture_revision",),
                name="tasks_closeout_prop_live_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="closeoutfielddecision",
            constraint=models.UniqueConstraint(
                fields=("proposal", "field_path"), name="tasks_closeout_decision_uniq"
            ),
        ),
    ]
