# Generated by Django 5.2.15 on 2026-07-23 17:58

"""KanbanColumn board-column model."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Introduce the KanbanColumn board-column model."""

    dependencies = [('tasks', '0008_closeoutamendment_closeoutcapture_and_more')]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'key',
                    models.SlugField(
                        help_text='Stable identifier stored in KanbanCard.status',
                        max_length=32,
                        unique=True,
                        verbose_name='Key',
                    ),
                ),
                ('label', models.CharField(max_length=64, verbose_name='Label')),
                (
                    'color',
                    models.CharField(
                        blank=True,
                        default='gray',
                        help_text='Mantine color name used for the column badge',
                        max_length=32,
                        verbose_name='Color',
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text='Left-to-right position on the board',
                        verbose_name='Order',
                    ),
                ),
                (
                    'is_default',
                    models.BooleanField(
                        default=False,
                        help_text='Seeded system column; protected from deletion',
                        verbose_name='Default',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kanban Column',
                'verbose_name_plural': 'Kanban Columns',
                'ordering': ['order', 'key'],
            },
        )
    ]
