# Generated by Django 5.2.15 on 2026-07-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_assetmaintenancerecord_work_order"),
        ("tasks", "0018_kanbancard_tags_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanbancard",
            name="affected_component",
            field=models.CharField(
                blank=True,
                help_text="The part of the asset this work concerns",
                max_length=200,
                verbose_name="Affected Component",
            ),
        ),
        migrations.AddField(
            model_name="kanbancard",
            name="affected_component_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External/human identifier for the component",
                max_length=64,
                verbose_name="Affected Component Reference",
            ),
        ),
        migrations.AddField(
            model_name="kanbancard",
            name="installed_part",
            field=models.ForeignKey(
                blank=True,
                help_text="Installed part this work concerns, when one is mapped",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="work_orders",
                to="assets.machinepart",
                verbose_name="Installed Part",
            ),
        ),
    ]
