# Generated by Django 5.2.15 on 2026-07-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_kanbancard_affected_component_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="kanbancard",
            table="tasks_workorder",
        ),
    ]
