"""Field metadata that moved with the rename.

Help text and a related name that still spoke of cards, plus the column key's
description of where a board status is stored. No column changes.
"""

# Generated by Django 5.2.15 on 2026-07-27 20:43

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Realign field metadata with the renamed models."""

    dependencies = [('tasks', '0021_rename_kanbancard_to_workorder')]

    operations = [
        migrations.AlterField(
            model_name='kanbancolumn',
            name='key',
            field=models.SlugField(
                help_text='Stable identifier stored in the board status field',
                max_length=32,
                unique=True,
                verbose_name='Key',
            ),
        ),
        migrations.AlterField(
            model_name='workorderdeletionrecord',
            name='work_order_pk',
            field=models.PositiveIntegerField(
                db_index=True, help_text='Primary key of the deleted WorkOrder'
            ),
        ),
        migrations.AlterField(
            model_name='workorderpart',
            name='quantity',
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal('1'),
                help_text='Required quantity of this part for the work order',
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name='workorderpart',
            name='work_order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='work_order_parts',
                to='tasks.workorder',
            ),
        ),
    ]
