# Generated by Django 5.2.15 on 2026-07-27 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0023_rename_stale_kanbancard_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'card_kind',
                    models.CharField(
                        choices=[
                            ('work_order', 'Work Order'),
                            ('subtask', 'Subtask'),
                            ('procurement', 'Procurement'),
                        ],
                        db_index=True,
                        default='work_order',
                        max_length=16,
                        verbose_name='Card Kind',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        db_index=True, max_length=32, verbose_name='Status'
                    ),
                ),
                (
                    'board_order',
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text='Position within the column',
                        verbose_name='Board Order',
                    ),
                ),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                (
                    'description',
                    models.TextField(blank=True, verbose_name='Description'),
                ),
                ('assignee', models.CharField(blank=True, max_length=120)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                (
                    'estimated_minutes',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'assigned_to',
                    models.ForeignKey(
                        blank=True,
                        help_text='Who does this piece; unset means the work order assignee',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_cards',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Assigned To',
                    ),
                ),
                (
                    'work_order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cards',
                        to='tasks.workorder',
                        verbose_name='Work Order',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Kanban Card',
                'verbose_name_plural': 'Kanban Cards',
                'ordering': ['board_order', 'created_at'],
                'indexes': [
                    models.Index(
                        fields=['work_order', 'status'], name='tasks_card_wo_status'
                    ),
                    models.Index(
                        fields=['status', 'board_order'], name='tasks_card_column'
                    ),
                ],
            },
        )
    ]
