"""Drop the fields that made a piece of work a second job.

``parent`` and ``card_kind`` are properties of a card now. Nothing can hold a
work order below another one, which is what "one work order per maintenance
job" means in the schema rather than only in the docs.
"""

# Generated by Django 5.2.15 on 2026-07-28 01:15

from django.db import migrations


class Migration(migrations.Migration):
    """Remove work-order composition, now that cards carry it."""

    dependencies = [
        ("tasks", "0026_children_become_cards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="card_kind",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="parent",
        ),
    ]
