# Generated by Django 5.2.15 on 2026-08-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0027_drop_workorder_parent_and_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobkit",
            options={
                "permissions": [
                    ("manage_jobkit", "Can manage job kits"),
                    ("reserve_jobkit", "Can reserve job kit stock"),
                    ("stage_jobkit", "Can stage job kits"),
                    ("issue_jobkit", "Can issue job kits"),
                    (
                        "approve_jobkit_substitution",
                        "Can approve job kit substitutions",
                    ),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="procedure",
            options={
                "permissions": [
                    ("author_procedure", "Can author procedures"),
                    ("review_procedure", "Can review procedures"),
                    ("publish_procedure", "Can publish procedures"),
                    ("apply_procedure", "Can apply procedures to work orders"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="workorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("plan_workorder", "Can plan work orders"),
                    ("assign_workorder", "Can assign work orders"),
                    ("transition_workorder", "Can transition work orders"),
                    ("execute_workorder", "Can execute work orders"),
                    ("complete_workorder", "Can complete work orders"),
                    ("view_workorder_audit", "Can view work order audit surfaces"),
                ],
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
            },
        ),
    ]
