# Generated by Django 5.2.15 on 2026-08-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0028_alter_jobkit_options_alter_procedure_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closeoutfielddecision",
            name="final_value",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
