# Generated by Django 5.2.16 on 2026-08-29 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0014_assetmaintenancerecord_assets_maint_machine_date"),
        ("company", "0080_company_tags"),
        ("tasks", "0029_alter_closeoutfielddecision_final_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["actual_completed_at"], name="tasks_wo_actual_completed"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["scheduled_start"], name="tasks_wo_sched_start"),
        ),
    ]
