# Generated by Django 5.2.15 on 2026-07-16 04:45
"""Enforce exactly one asset-history row per work order (Feature #15)."""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Promote the nullable work-order FK to a nullable one-to-one."""

    dependencies = [
        ("assets", "0004_dedupe_maintenance_work_orders"),
        ("tasks", "0008_closeoutamendment_closeoutcapture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetmaintenancerecord",
            name="work_order",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked Kanban card / work order (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_record",
                to="tasks.kanbancard",
                verbose_name="Work Order",
            ),
        ),
    ]
