# Generated by Django 5.2.15 on 2026-07-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_assetmaintenancerecord_work_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Client name",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable identifier used for scope and integrations",
                        max_length=64,
                        unique=True,
                        verbose_name="Client Code",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="assetmachine",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client this internal asset belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="machines",
                to="assets.client",
                verbose_name="Client",
            ),
        ),
    ]
