# Generated by Django 5.2.15 on 2026-07-27 17:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_client_assetmachine_client"),
        ("company", "0080_company_tags"),
        ("tasks", "0019_kanbancard_affected_component_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="Name"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("iot", "IoT"),
                            ("scada", "SCADA"),
                            ("plc", "PLC"),
                            ("dcs", "DCS"),
                            ("mes", "MES"),
                            ("bas_bms", "BAS / BMS"),
                            ("ems", "EMS"),
                            ("iiot", "IIoT"),
                            ("historian", "Historian"),
                            ("webhook", "Webhook"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        blank=True,
                        help_text="Registered connector adapter key",
                        max_length=64,
                        verbose_name="Connector",
                    ),
                ),
                (
                    "secret_ref",
                    models.CharField(
                        blank=True,
                        help_text="Deployment-managed secret reference; never a credential",
                        max_length=200,
                        verbose_name="Secret Reference",
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="Config"),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "site_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Site Key",
                    ),
                ),
                (
                    "freshness_threshold_seconds",
                    models.PositiveIntegerField(
                        default=900,
                        help_text="Signals older than this are shown as stale",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Freshness Threshold",
                    ),
                ),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_sources",
                        to="company.company",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Source",
                "verbose_name_plural": "Health Sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MachineSignalBinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_key",
                    models.CharField(
                        db_index=True,
                        help_text="Tag / point identifier in the source system",
                        max_length=255,
                        verbose_name="External Key",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="Display Name"),
                ),
                (
                    "signal_kind",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g. current, vibration, pressure, temperature, level",
                        max_length=64,
                        verbose_name="Signal Kind",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=32, verbose_name="Unit"),
                ),
                ("normal_min", models.FloatField(blank=True, null=True)),
                ("normal_max", models.FloatField(blank=True, null=True)),
                ("warn_min", models.FloatField(blank=True, null=True)),
                ("warn_max", models.FloatField(blank=True, null=True)),
                ("critical_min", models.FloatField(blank=True, null=True)),
                ("critical_max", models.FloatField(blank=True, null=True)),
                (
                    "transform",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Transform"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_bindings",
                        to="assets.assetmachine",
                        verbose_name="Machine",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="assets.healthsource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Signal Binding",
                "verbose_name_plural": "Machine Signal Bindings",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="MachineAnomaly",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("alarm_code", models.CharField(blank=True, max_length=64)),
                ("fingerprint", models.CharField(db_index=True, max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=12,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("suppressed", "Suppressed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "evidence_summary",
                    models.TextField(blank=True, verbose_name="Evidence"),
                ),
                (
                    "metrics",
                    models.JSONField(blank=True, default=dict, verbose_name="Metrics"),
                ),
                (
                    "detector",
                    models.CharField(
                        blank=True,
                        help_text="Rule or model that raised this anomaly",
                        max_length=64,
                    ),
                ),
                ("detector_version", models.CharField(blank=True, max_length=32)),
                ("first_observed_at", models.DateTimeField(db_index=True)),
                ("last_observed_at", models.DateTimeField(db_index=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledgement_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="assets.assetmachine",
                        verbose_name="Machine",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomalies",
                        to="assets.healthsource",
                        verbose_name="Source",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomalies",
                        to="tasks.kanbancard",
                        verbose_name="Work Order",
                    ),
                ),
                (
                    "bindings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="anomalies",
                        to="assets.machinesignalbinding",
                        verbose_name="Signals",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Anomaly",
                "verbose_name_plural": "Machine Anomalies",
                "ordering": ["-last_observed_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthEvidenceSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signal_label", models.CharField(blank=True, max_length=200)),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "samples",
                    models.JSONField(blank=True, default=list, verbose_name="Samples"),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Statistics"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("uncertain", "Uncertain"),
                            ("bad", "Bad"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=12,
                        verbose_name="Quality",
                    ),
                ),
                (
                    "stale",
                    models.BooleanField(
                        default=False,
                        help_text="The window was already stale when captured",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual_repair", "Manual repair"),
                            ("anomaly_repair", "Anomaly repair"),
                            ("ai_diagnosis", "AI diagnosis"),
                            ("confirmation_test", "Confirmation test"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("source_references", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("system_actor", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_snapshots",
                        to="assets.assetmachine",
                        verbose_name="Machine",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="assets.healthsource",
                        verbose_name="Source",
                    ),
                ),
                (
                    "anomaly",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="assets.machineanomaly",
                        verbose_name="Anomaly",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="assets.machinesignalbinding",
                        verbose_name="Binding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Evidence Snapshot",
                "verbose_name_plural": "Health Evidence Snapshots",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="MachineSignalState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.JSONField(blank=True, default=dict, verbose_name="Value"),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        db_index=True, help_text="When the source observed the value"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When AIMMS accepted the value",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("uncertain", "Uncertain"),
                            ("bad", "Bad"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=12,
                        verbose_name="Quality",
                    ),
                ),
                ("source_sequence", models.BigIntegerField(blank=True, null=True)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "binding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="assets.machinesignalbinding",
                        verbose_name="Binding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Signal State",
                "verbose_name_plural": "Machine Signal States",
            },
        ),
        migrations.AddIndex(
            model_name="machinesignalbinding",
            index=models.Index(
                fields=["machine", "active"], name="assets_mach_machine_a10e4e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="machinesignalbinding",
            constraint=models.UniqueConstraint(
                fields=("machine", "source", "external_key"),
                name="machine_health_binding_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="machineanomaly",
            index=models.Index(
                fields=["machine", "status"], name="assets_mach_machine_e9b8a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="machineanomaly",
            index=models.Index(
                fields=["machine", "severity", "status"],
                name="assets_mach_machine_02a438_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="machineanomaly",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["open", "acknowledged"])),
                fields=("machine", "fingerprint"),
                name="machine_health_anomaly_open_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="healthevidencesnapshot",
            index=models.Index(
                fields=["machine", "captured_at"], name="assets_heal_machine_b377b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthevidencesnapshot",
            index=models.Index(
                fields=["anomaly", "captured_at"], name="assets_heal_anomaly_5f91f7_idx"
            ),
        ),
    ]
