# Generated by Django 5.2.16 on 2026-09-10 19:18
"""Add public equipment identities, occurrences and draft dictionary models."""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_equipment_uuids(apps, schema_editor):
    """Generate independent UUIDs on the migration database, not a shared default."""
    model = apps.get_model('assets', 'AssetMachine')
    queryset = model.objects.using(schema_editor.connection.alias)
    for pk in (
        queryset.filter(uuid__isnull=True).values_list('pk', flat=True).iterator()
    ):
        queryset.filter(pk=pk).update(uuid=uuid.uuid4())


class Migration(migrations.Migration):
    """Preserve existing asset primary keys while adding the registry schema."""

    dependencies = [
        ('assets', '0010_remove_assetmachine_customer'),
        ('common', '0049_merge_upstream_sync'),
        ('part', '0154_partverificationsession_scope_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft inference'),
                            ('verified', 'Verified assignment'),
                        ],
                        default='draft',
                        max_length=16,
                    ),
                ),
                ('provenance', models.CharField(blank=True, max_length=250)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['machine_id', 'code']},
        ),
        migrations.CreateModel(
            name='DictionaryPoint',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('path', models.CharField(max_length=500)),
                ('raw_tag', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('match_method', models.CharField(default='unresolved', max_length=16)),
                ('issue', models.CharField(blank=True, max_length=250)),
                ('data_type', models.CharField(default='unknown', max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('unit_status', models.CharField(default='unresolved', max_length=16)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Draft'),
                            ('approved', 'Approved'),
                            ('unresolved', 'Unresolved'),
                            ('rejected', 'Rejected'),
                        ],
                        default='draft',
                        max_length=16,
                    ),
                ),
                ('source_hash', models.CharField(max_length=64)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['machine_id', 'path']},
        ),
        migrations.AddField(
            model_name='assetmachine',
            name='asset_type',
            field=models.CharField(
                choices=[
                    ('equipment', 'Equipment'),
                    ('pumphouse', 'Pump station'),
                    ('pump', 'Pump'),
                ],
                db_index=True,
                default='equipment',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='assetmachine',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='children',
                to='assets.assetmachine',
            ),
        ),
        migrations.AddField(
            model_name='assetmachine',
            name='source_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assetmachine',
            name='source_entity_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmachine',
            name='source_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assetmachine',
            name='source_namespace',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='assetmachine',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(backfill_equipment_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='assetmachine',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='assetmachine',
            constraint=models.UniqueConstraint(
                condition=models.Q(('asset_type', 'pumphouse')),
                fields=('source_namespace', 'source_entity_uuid'),
                name='registry_source_station_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='assetmachine',
            constraint=models.UniqueConstraint(
                condition=models.Q(('asset_type', 'pump')),
                fields=('parent', 'source_key'),
                name='registry_pump_slot_unique',
            ),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='machine',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='components',
                to='assets.assetmachine',
            ),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='part',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='part.part'
            ),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='dictionarypoint',
            name='component',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='assets.assetcomponent',
            ),
        ),
        migrations.AddField(
            model_name='dictionarypoint',
            name='machine',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='owned_points',
                to='assets.assetmachine',
            ),
        ),
        migrations.AddField(
            model_name='dictionarypoint',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='dictionarypoint',
            name='station',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='dictionary_points',
                to='assets.assetmachine',
            ),
        ),
        migrations.AddField(
            model_name='dictionarypoint',
            name='template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='common.parametertemplate',
            ),
        ),
        migrations.AddConstraint(
            model_name='assetcomponent',
            constraint=models.UniqueConstraint(
                fields=('machine', 'code'), name='registry_component_slot_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='dictionarypoint',
            constraint=models.UniqueConstraint(
                fields=('station', 'path'), name='registry_dictionary_path_unique'
            ),
        ),
    ]
