# Generated by Django 5.2.16 on 2026-08-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_assetmachine_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetmachine",
            name="barcode_data",
            field=models.CharField(
                blank=True,
                help_text="Third party barcode data",
                max_length=500,
                verbose_name="Barcode Data",
            ),
        ),
        migrations.AddField(
            model_name="assetmachine",
            name="barcode_hash",
            field=models.CharField(
                blank=True,
                help_text="Unique hash of barcode data",
                max_length=128,
                verbose_name="Barcode Hash",
            ),
        ),
    ]
