# Generated by Django 5.2.16 on 2026-09-11 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_equipment_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionCheckpoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_uuid",
                    models.CharField(
                        db_index=True,
                        help_text="Station identifier in the source system",
                        max_length=64,
                        verbose_name="Station UUID",
                    ),
                ),
                (
                    "hour_bucket",
                    models.CharField(
                        help_text="Hour bucket last read, epoch milliseconds",
                        max_length=20,
                        verbose_name="Hour Bucket",
                    ),
                ),
                (
                    "sub_time_period",
                    models.BigIntegerField(
                        help_text="Last sample read within the bucket, epoch milliseconds",
                        verbose_name="Sample Timestamp",
                    ),
                ),
                (
                    "continuation_token",
                    models.TextField(
                        blank=True,
                        help_text="Opaque provider resume token; never a credential",
                        verbose_name="Continuation Token",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_checkpoints",
                        to="assets.healthsource",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Checkpoint",
                "verbose_name_plural": "Ingestion Checkpoints",
                "ordering": ["source_id", "station_uuid"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "station_uuid"),
                        name="assets_ingestion_checkpoint_unique",
                    )
                ],
            },
        ),
    ]
