# Generated by Django 5.2.17 on 2026-09-14 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0012_ingestioncheckpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="last_error_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="last_poll_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="last_success_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="scan_until",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_checkpoints",
                to="assets.assetmachine",
            ),
        ),
    ]
