# Generated by Django 5.2.16 on 2026-08-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_clientscopegrant"),
        ("tasks", "0029_alter_closeoutfielddecision_final_value"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assetmaintenancerecord",
            index=models.Index(
                fields=["machine", "date"], name="assets_maint_machine_date"
            ),
        ),
    ]
