# Generated by Django 5.2.17 on 2026-09-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_station_poll_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthsource",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client authorized to activate stations on this source",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="health_sources",
                to="assets.client",
            ),
        ),
        migrations.AddField(
            model_name="ingestioncheckpoint",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="machinesignalbinding",
            name="dictionary_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="machinesignalbinding",
            name="dictionary_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signal_bindings",
                to="assets.dictionarypoint",
            ),
        ),
        migrations.AlterField(
            model_name="machinesignalbinding",
            name="display_name",
            field=models.CharField(max_length=255, verbose_name="Display Name"),
        ),
        migrations.AlterField(
            model_name="machinesignalbinding",
            name="external_key",
            field=models.CharField(
                db_index=True,
                help_text="Tag / point identifier in the source system",
                max_length=500,
                verbose_name="External Key",
            ),
        ),
    ]
