# Generated by Django 5.2.16 on 2026-08-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0014_assetmaintenancerecord_assets_maint_machine_date"),
        ("tasks", "0030_workorder_tasks_wo_actual_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineanomaly",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalies",
                to="tasks.workorder",
                verbose_name="Work Order",
            ),
        ),
    ]
