# Generated by Django 5.2.17 on 2026-09-24 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0015_alter_machineanomaly_work_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assetmachine",
            name="placement_version",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="client",
            name="location_revision",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name="AssetLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.SlugField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("site", "Site"),
                            ("facility", "Facility"),
                            ("building", "Building"),
                            ("area", "Area"),
                            ("line", "Production Line"),
                            ("cell", "Cell"),
                            ("room", "Room"),
                            ("other", "Other"),
                        ],
                        default="site",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("name_key", models.CharField(editable=False, max_length=255)),
                ("sibling_key", models.CharField(editable=False, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="assets.client"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="assets.assetlocation",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="assetmachine",
            name="physical_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="machines",
                to="assets.assetlocation",
            ),
        ),
        migrations.CreateModel(
            name="LocationParentHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(max_length=1000)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_history",
                        to="assets.assetlocation",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assetlocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineLocationTransfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("payload", models.JSONField()),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="assets.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachinePlacementHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.assetlocation",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement_history",
                        to="assets.assetmachine",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.machinelocationtransfer",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="assetlocation",
            constraint=models.UniqueConstraint(
                fields=("client", "code"), name="assets_location_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetlocation",
            constraint=models.UniqueConstraint(
                fields=("client", "sibling_key", "name_key"),
                name="assets_location_sibling",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetlocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("pk")), _negated=True),
                name="assets_location_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationparenthistory",
            constraint=models.UniqueConstraint(
                fields=("location", "valid_from"), name="assets_parent_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationparenthistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="assets_parent_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="machinelocationtransfer",
            constraint=models.UniqueConstraint(
                fields=("client", "actor", "idempotency_key"),
                name="assets_transfer_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="machineplacementhistory",
            constraint=models.UniqueConstraint(
                fields=("machine", "valid_from"), name="assets_placement_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="machineplacementhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="assets_placement_interval",
            ),
        ),
    ]
