# Generated by Django 5.2.17 on 2026-09-26 03:45
"""Create durable demo sessions, provenance, receipts and history tables."""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Introduce the bounded synthetic demo schema."""

    dependencies = [
        ('assets', '0016_assetmachine_placement_version_and_more'),
        ('tasks', '0030_workorder_tasks_wo_actual_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoMetricsCoverageInterval',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('event_key', models.CharField(max_length=128)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('fully_observed', models.BooleanField(default=True)),
                ('planned', models.BooleanField(default=True)),
                ('location_alias', models.CharField(blank=True, max_length=64)),
                (
                    'attribution_mode',
                    models.CharField(default='synthetic_scenario', max_length=32),
                ),
                (
                    'machine',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='demo_coverage_intervals',
                        to='assets.assetmachine',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Demo Metrics Coverage Interval',
                'verbose_name_plural': 'Demo Metrics Coverage Intervals',
            },
        ),
        migrations.CreateModel(
            name='DemoMetricsSession',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('dataset_key', models.CharField(db_index=True, max_length=64)),
                ('session_key', models.CharField(max_length=64)),
                (
                    'mode',
                    models.CharField(
                        choices=[
                            ('current_demo', 'Integrated current demo'),
                            ('historical_demo', 'Integrated historical demo'),
                        ],
                        default='current_demo',
                        max_length=32,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('stopped', 'Stopped'),
                            ('expired', 'Expired'),
                            ('cleaned', 'Cleaned'),
                        ],
                        db_index=True,
                        default='active',
                        max_length=16,
                    ),
                ),
                ('fixture_version', models.CharField(max_length=32)),
                ('fixture_canonical_sha256', models.CharField(max_length=64)),
                ('fixture_file_sha256', models.CharField(max_length=64)),
                ('mapping_sha256', models.CharField(max_length=64)),
                ('plan_sha256', models.CharField(max_length=64)),
                ('target_fingerprint', models.CharField(max_length=255)),
                ('code_identity', models.CharField(blank=True, max_length=255)),
                ('demo_owner_identity', models.CharField(blank=True, max_length=255)),
                ('anchor_at', models.DateTimeField()),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('effect_policy', models.JSONField(blank=True, default=list)),
                ('plan_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                (
                    'demo_owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='demo_metrics_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Demo Metrics Session',
                'verbose_name_plural': 'Demo Metrics Sessions',
            },
        ),
        migrations.CreateModel(
            name='DemoMetricsReceipt',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'operation_kind',
                    models.CharField(
                        choices=[
                            ('apply_source', 'Create source'),
                            ('apply_binding', 'Create binding'),
                            ('apply_work_order', 'Create work order'),
                            ('apply_control', 'Import synthetic control'),
                            ('apply_observation', 'Ingest observation'),
                            ('replay_observation', 'Replay observation'),
                            ('stop', 'Stop session'),
                            ('cleanup', 'Cleanup session'),
                        ],
                        max_length=32,
                    ),
                ),
                ('item_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                (
                    'outcome',
                    models.CharField(
                        choices=[
                            ('applied', 'Applied'),
                            ('replayed', 'Replayed without new effects'),
                        ],
                        max_length=16,
                    ),
                ),
                ('effect_ids', models.JSONField(blank=True, default=list)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='receipts',
                        to='assets.demometricssession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Demo Metrics Receipt',
                'verbose_name_plural': 'Demo Metrics Receipts',
            },
        ),
        migrations.CreateModel(
            name='DemoMetricsObject',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'kind',
                    models.CharField(
                        choices=[
                            ('work_order', 'Work Order'),
                            ('source', 'Health Source'),
                            ('binding', 'Signal Binding'),
                            ('anomaly', 'Anomaly'),
                            ('coverage_interval', 'Coverage Interval'),
                            ('downtime_interval', 'Downtime Interval'),
                        ],
                        max_length=32,
                    ),
                ),
                ('fixture_key', models.CharField(max_length=128)),
                (
                    'origin',
                    models.CharField(
                        choices=[
                            ('created', 'Created by this session'),
                            ('referenced', 'Referenced existing record'),
                        ],
                        max_length=16,
                    ),
                ),
                ('seed_fingerprint', models.CharField(blank=True, max_length=64)),
                ('last_fingerprint', models.CharField(blank=True, max_length=64)),
                ('target_version', models.IntegerField(default=0)),
                ('dependent_refs', models.JSONField(blank=True, default=list)),
                (
                    'binding',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='demo_metric_objects',
                        to='assets.machinesignalbinding',
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='demo_metric_objects',
                        to='assets.healthsource',
                    ),
                ),
                (
                    'work_order',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='demo_metric_objects',
                        to='tasks.workorder',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ledger_objects',
                        to='assets.demometricssession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Demo Metrics Object',
                'verbose_name_plural': 'Demo Metrics Objects',
            },
        ),
        migrations.CreateModel(
            name='DemoMetricsMachine',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('alias', models.CharField(max_length=64)),
                ('client_code', models.CharField(max_length=64)),
                ('placement_id', models.IntegerField(blank=True, null=True)),
                ('placement_version', models.BigIntegerField(default=0)),
                ('ownership_evidence', models.JSONField(blank=True, default=dict)),
                ('expected_fingerprint', models.CharField(blank=True, max_length=64)),
                ('claim_active', models.BooleanField(default=True)),
                (
                    'machine',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='demo_metric_memberships',
                        to='assets.assetmachine',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='machines',
                        to='assets.demometricssession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Demo Metrics Machine',
                'verbose_name_plural': 'Demo Metrics Machines',
            },
        ),
        migrations.CreateModel(
            name='DemoMetricsDowntimeInterval',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('event_key', models.CharField(max_length=128)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('loss_category', models.CharField(max_length=64)),
                ('failure_key', models.CharField(blank=True, max_length=128)),
                ('location_alias', models.CharField(blank=True, max_length=64)),
                (
                    'attribution_mode',
                    models.CharField(default='synthetic_scenario', max_length=32),
                ),
                (
                    'coverage',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='downtime_events',
                        to='assets.demometricscoverageinterval',
                    ),
                ),
                (
                    'machine',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='demo_downtime_intervals',
                        to='assets.assetmachine',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='downtime_intervals',
                        to='assets.demometricssession',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Demo Metrics Downtime Interval',
                'verbose_name_plural': 'Demo Metrics Downtime Intervals',
            },
        ),
        migrations.AddField(
            model_name='demometricscoverageinterval',
            name='session',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coverage_intervals',
                to='assets.demometricssession',
            ),
        ),
        migrations.AddIndex(
            model_name='demometricssession',
            index=models.Index(
                fields=['status', 'expires_at'], name='demometrics_session_status'
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricssession',
            constraint=models.UniqueConstraint(
                fields=('dataset_key', 'session_key'),
                name='demometrics_session_key_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='demometricsreceipt',
            index=models.Index(
                fields=['operation_kind', 'item_key'],
                name='demometrics_receipt_identity',
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricsreceipt',
            constraint=models.UniqueConstraint(
                fields=('session', 'operation_kind', 'item_key'),
                name='demometrics_receipt_key_uniq',
            ),
        ),
        migrations.AddIndex(
            model_name='demometricsobject',
            index=models.Index(
                fields=['session', 'kind'], name='demometrics_object_kind'
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricsobject',
            constraint=models.UniqueConstraint(
                fields=('session', 'kind', 'fixture_key'),
                name='demometrics_object_key_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricsobject',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('kind', 'work_order'),
                        ('work_order__isnull', False),
                        ('source__isnull', True),
                        ('binding__isnull', True),
                    ),
                    models.Q(
                        ('kind', 'source'),
                        ('source__isnull', False),
                        ('work_order__isnull', True),
                        ('binding__isnull', True),
                    ),
                    models.Q(
                        ('kind', 'binding'),
                        ('binding__isnull', False),
                        ('work_order__isnull', True),
                        ('source__isnull', True),
                    ),
                    models.Q(
                        (
                            'kind__in',
                            ['anomaly', 'coverage_interval', 'downtime_interval'],
                        ),
                        ('work_order__isnull', True),
                        ('source__isnull', True),
                        ('binding__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='demometrics_object_target_consistent',
            ),
        ),
        migrations.AddIndex(
            model_name='demometricsmachine',
            index=models.Index(
                fields=['session', 'alias'], name='demometrics_machine_lookup'
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricsmachine',
            constraint=models.UniqueConstraint(
                fields=('session', 'alias'), name='demometrics_machine_alias_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricsmachine',
            constraint=models.UniqueConstraint(
                fields=('session', 'machine'), name='demometrics_machine_machine_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricsmachine',
            constraint=models.UniqueConstraint(
                condition=models.Q(('claim_active', True)),
                fields=('machine',),
                name='demometrics_machine_active_claim',
            ),
        ),
        migrations.AddIndex(
            model_name='demometricsdowntimeinterval',
            index=models.Index(
                fields=['session', 'machine', 'start_at'],
                name='demometrics_downtime_query',
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricsdowntimeinterval',
            constraint=models.UniqueConstraint(
                fields=('session', 'event_key'), name='demometrics_downtime_key_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricsdowntimeinterval',
            constraint=models.CheckConstraint(
                condition=models.Q(('end_at__gt', models.F('start_at'))),
                name='demometrics_downtime_interval_positive',
            ),
        ),
        migrations.AddIndex(
            model_name='demometricscoverageinterval',
            index=models.Index(
                fields=['session', 'machine', 'start_at'],
                name='demometrics_coverage_query',
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricscoverageinterval',
            constraint=models.UniqueConstraint(
                fields=('session', 'event_key'), name='demometrics_coverage_key_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='demometricscoverageinterval',
            constraint=models.CheckConstraint(
                condition=models.Q(('end_at__gt', models.F('start_at'))),
                name='demometrics_coverage_interval_positive',
            ),
        ),
    ]
