"""Auto-generated database migration."""

# Generated by Django 5.2.15 on 2026-07-15 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import aichat.models


class Migration(migrations.Migration):
    """Migration."""
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatThread",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=aichat.models.generate_thread_id,
                        editable=False,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope_key", models.CharField(max_length=255)),
                ("scope_hash", models.CharField(max_length=64)),
                (
                    "namespace",
                    models.CharField(
                        choices=[("unscoped", "Unscoped"), ("scoped", "Scoped")],
                        default="unscoped",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "last_workflow",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("next_sequence", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_chat_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=aichat.models.generate_message_id,
                        editable=False,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "modality",
                    models.CharField(
                        choices=[("text", "Text"), ("voice", "Voice")],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="aichat.chatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="ChatTurn",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=aichat.models.generate_turn_id,
                        editable=False,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[("text", "Text"), ("voice", "Voice")], max_length=16
                    ),
                ),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("trusted_context", models.JSONField(blank=True, default=dict)),
                ("modality_metadata", models.JSONField(blank=True, default=dict)),
                ("canonical_result", models.JSONField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("incomplete", "Incomplete"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "input_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_for_turn",
                        to="aichat.chatmessage",
                    ),
                ),
                (
                    "output_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_for_turn",
                        to="aichat.chatmessage",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="aichat.chatthread",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["owner", "scope_hash", "namespace", "-updated_at"],
                name="aichat_thread_boundary_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatthread",
            index=models.Index(
                fields=["owner", "scope_key", "namespace"],
                name="aichat_thread_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_key", ""), _negated=True),
                name="aichat_thread_scope_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_hash", ""), _negated=True),
                name="aichat_thread_hash_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_sequence__gte", 1)),
                name="aichat_thread_next_sequence_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatthread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("id__startswith", "scoped_"), ("namespace", "scoped")),
                    models.Q(
                        ("namespace", "unscoped"),
                        models.Q(("id__startswith", "scoped_"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="aichat_thread_namespace_id",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["thread", "sequence"], name="aichat_message_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.UniqueConstraint(
                fields=("thread", "sequence"),
                name="aichat_message_thread_sequence_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="aichat_message_sequence_gte_1",
            ),
        ),
        migrations.AddIndex(
            model_name="chatturn",
            index=models.Index(
                fields=["thread", "created_at"], name="aichat_turn_thread_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatturn",
            index=models.Index(
                fields=["thread", "state", "created_at"],
                name="aichat_turn_state_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatturn",
            constraint=models.UniqueConstraint(
                fields=("thread", "idempotency_key"),
                name="aichat_turn_thread_idempotency_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                name="aichat_turn_idempotency_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_fingerprint", ""), _negated=True),
                name="aichat_turn_fingerprint_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatturn",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("canonical_result__isnull", True),
                        ("completed_at__isnull", True),
                        ("output_message__isnull", True),
                        ("state", "running"),
                    ),
                    models.Q(
                        ("canonical_result__isnull", False),
                        ("completed_at__isnull", False),
                        ("output_message__isnull", False),
                        ("state__in", ("complete", "incomplete", "canceled", "failed")),
                    ),
                    _connector="OR",
                ),
                name="aichat_turn_terminal_result_state",
            ),
        ),
    ]
