"""Auto-generated database migration."""

# Generated by Django 5.2.15 on 2026-07-15 13:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""
    dependencies = [
        ("aichat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatActionProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope_key", models.CharField(max_length=255)),
                ("scope_hash", models.CharField(max_length=64)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("source_turn_id", models.CharField(blank=True, max_length=64)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("work_order.hold", "Hold work order"),
                            ("work_order.resume", "Resume work order"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_work_order_id", models.PositiveIntegerField()),
                ("target_version", models.PositiveIntegerField()),
                ("preview", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("executed", "Executed"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("policy_version", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("receipt", models.JSONField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_action_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "state", "expires_at"],
                        name="aichat_proposal_review_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "idempotency_key"),
                        name="aichat_proposal_intent_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("receipt__isnull", False), ("state", "executed")),
                            models.Q(("state", "executed"), _negated=True),
                            _connector="OR",
                        ),
                        name="aichat_proposal_executed_receipt",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scope_hash", ""), _negated=True),
                        name="aichat_proposal_scope_required",
                    ),
                ],
            },
        ),
    ]
