"""Auto-generated database migration."""

# Generated by Django 5.2.15 on 2026-07-16 04:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Scoped-chat governance rows (Feature #14)."""

    dependencies = [
        ('aichat', '0002_chatactionproposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopedConversation',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('context_type', models.CharField(db_index=True, max_length=32)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('scope_key', models.CharField(max_length=255)),
                ('scope_hash', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('read_only', 'Read only'),
                            ('closed', 'Closed'),
                            ('deleted', 'Deleted'),
                        ],
                        default='active',
                        max_length=16,
                    ),
                ),
                ('ai_thread_id', models.CharField(max_length=80, unique=True)),
                (
                    'last_context_revision',
                    models.CharField(blank=True, default='', max_length=128),
                ),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scoped_conversations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.CreateModel(
            name='ChatToolInvocation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('turn_key', models.CharField(db_index=True, max_length=64)),
                ('tool', models.CharField(max_length=64)),
                (
                    'tool_version',
                    models.CharField(blank=True, default='', max_length=16),
                ),
                ('arguments_redacted', models.JSONField(blank=True, default=dict)),
                (
                    'authorization_result',
                    models.CharField(
                        choices=[('allowed', 'Allowed'), ('denied', 'Denied')],
                        max_length=16,
                    ),
                ),
                (
                    'output_hash',
                    models.CharField(blank=True, default='', max_length=64),
                ),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'conversation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='tool_invocations',
                        to='aichat.scopedconversation',
                    ),
                ),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='ChatCitation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('turn_key', models.CharField(db_index=True, max_length=64)),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=64)),
                (
                    'source_revision',
                    models.CharField(blank=True, default='', max_length=128),
                ),
                ('locator', models.JSONField(blank=True, default=dict)),
                (
                    'excerpt_hash',
                    models.CharField(blank=True, default='', max_length=64),
                ),
                (
                    'authorization_class',
                    models.CharField(blank=True, default='', max_length=32),
                ),
                ('as_of', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'conversation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='citations',
                        to='aichat.scopedconversation',
                    ),
                ),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='ScopedConversationGrant',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'access',
                    models.CharField(
                        choices=[('read', 'Read'), ('export', 'Export')], max_length=16
                    ),
                ),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'conversation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='access_grants',
                        to='aichat.scopedconversation',
                    ),
                ),
                (
                    'granted_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'grantee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='scopedconversation',
            index=models.Index(
                fields=['owner', 'scope_hash', 'context_type', 'object_id'],
                name='aichat_conv_boundary_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='scopedconversation',
            constraint=models.CheckConstraint(
                condition=models.Q(('ai_thread_id__startswith', 'scoped_')),
                name='aichat_conv_scoped_thread_id',
            ),
        ),
        migrations.AddConstraint(
            model_name='scopedconversation',
            constraint=models.CheckConstraint(
                condition=models.Q(('scope_hash', ''), _negated=True),
                name='aichat_conv_scope_required',
            ),
        ),
        migrations.AddConstraint(
            model_name='scopedconversation',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('deleted_at__isnull', False), ('status', 'deleted')),
                    models.Q(('status', 'deleted'), _negated=True),
                    _connector='OR',
                ),
                name='aichat_conv_deleted_marker',
            ),
        ),
        migrations.AddIndex(
            model_name='chattoolinvocation',
            index=models.Index(
                fields=['conversation', 'turn_key'], name='aichat_tool_turn_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='chatcitation',
            index=models.Index(
                fields=['conversation', 'turn_key'], name='aichat_citation_turn_idx'
            ),
        ),
    ]
