# Generated by Django 5.2.15 on 2026-07-24 04:30

"""ChatActionProposal nullable target + intent parameters."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Make the proposal target nullable and add intent."""

    dependencies = [('aichat', '0003_scoped_chat_governance')]

    operations = [
        migrations.AddField(
            model_name='chatactionproposal',
            name='intent',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatactionproposal',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('work_order.hold', 'Hold work order'),
                    ('work_order.resume', 'Resume work order'),
                    ('work_order.schedule', 'Schedule work order'),
                    ('work_order.resize', 'Resize work order'),
                    ('work_order.update', 'Update work order plan'),
                    ('work_order.assign', 'Assign work order'),
                    ('work_order.delete', 'Delete work order'),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='chatactionproposal',
            name='target_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatactionproposal',
            name='target_work_order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
