# Generated by Django 5.2.15 on 2026-07-24 05:46

"""ChatActionProposal action_type choice set."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Extend the governed action choice set."""

    dependencies = [('aichat', '0004_chatactionproposal_intent_and_more')]

    operations = [
        migrations.AlterField(
            model_name='chatactionproposal',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('work_order.hold', 'Hold work order'),
                    ('work_order.resume', 'Resume work order'),
                    ('work_order.schedule', 'Schedule work order'),
                    ('work_order.resize', 'Resize work order'),
                    ('work_order.update', 'Update work order plan'),
                    ('work_order.assign', 'Assign work order'),
                    ('work_order.delete', 'Delete work order'),
                    ('work_order.cancel', 'Cancel work order'),
                    ('work_order.transition', 'Transition work order lifecycle'),
                    ('work_order.create', 'Create work order'),
                    ('work_order.create_child', 'Create child work order'),
                    ('work_order.generate_procurement', 'Generate procurement child'),
                    ('dependency.create', 'Create dependency'),
                    ('dependency.delete', 'Delete dependency'),
                    ('schedule.optimize', 'Optimize schedule (bulk)'),
                ],
                max_length=32,
            ),
        )
    ]
