# Generated by Django 5.2.15 on 2026-07-27 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0006_alter_chatactionproposal_action_type"),
        ("approvals", "0005_alter_approval_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatactionproposal",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_proposals",
                to="approvals.approval",
            ),
        ),
    ]
