# Generated by Django 5.2.15 on 2026-07-27 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0007_chatactionproposal_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlledDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_id", models.CharField(max_length=128)),
                ("revision", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("document_class", models.CharField(max_length=128)),
                ("scope_key", models.CharField(max_length=255)),
                ("scope_hash", models.CharField(max_length=64)),
                ("access_class", models.CharField(max_length=64)),
                ("source_filename", models.CharField(max_length=255)),
                ("source_location", models.CharField(max_length=1024)),
                (
                    "source_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("revision_date", models.DateField(blank=True, null=True)),
                ("facility", models.CharField(blank=True, default="", max_length=255)),
                (
                    "process_area",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("asset_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "child_asset_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "work_order_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "repair_packet_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("indexing", "Indexing"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "search_index_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "indexing_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_documents_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_documents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scope_key", "document_id", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope_hash", "document_id", "state"],
                        name="aichat_ctrl_doc_scope_idx",
                    ),
                    models.Index(
                        fields=["asset_id", "state"], name="aichat_ctrl_doc_asset_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope_key", "document_id", "revision"),
                        name="aichat_ctrl_doc_revision_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("scope_key", "document_id"),
                        name="aichat_ctrl_doc_current_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("document_id", ""), _negated=True),
                        name="aichat_ctrl_doc_id_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision", ""), _negated=True),
                        name="aichat_ctrl_doc_revision_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scope_key", ""), _negated=True),
                        name="aichat_ctrl_doc_scope_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scope_hash", ""), _negated=True),
                        name="aichat_ctrl_doc_hash_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_current", True), _negated=True),
                            ("state", "indexed"),
                            _connector="OR",
                        ),
                        name="aichat_ctrl_doc_current_indexed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "indexed"), _negated=True),
                            models.Q(
                                models.Q(("source_sha256", ""), _negated=True),
                                models.Q(("search_index_name", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="aichat_ctrl_doc_indexed_source",
                    ),
                ],
            },
        ),
    ]
