# Generated by Django 5.2.15 on 2026-07-27 23:18

import uuid
from django.db import migrations, models


def backfill_selection_ids(apps, schema_editor):
    """Assign a distinct opaque selection identifier to existing documents."""
    ControlledDocument = apps.get_model('aichat', 'ControlledDocument')
    for document in ControlledDocument.objects.filter(selection_id__isnull=True).iterator():
        selection_id = uuid.uuid4()
        while ControlledDocument.objects.filter(selection_id=selection_id).exists():
            selection_id = uuid.uuid4()
        document.selection_id = selection_id
        document.save(update_fields=['selection_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0008_controlleddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlleddocument",
            name="selection_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_selection_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="controlleddocument",
            name="selection_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
