# Generated by Django 5.2.15 on 2026-07-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0009_controlleddocument_selection_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="scopedconversation",
            name="selected_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scoped_conversations",
                to="aichat.controlleddocument",
            ),
        ),
    ]
