# Generated by Django 5.2.16 on 2026-08-11 23:04
"""S36 correlation spine (additive, reversible).

Forward: add ChatActionProposal.correlation_id (indexed CharField, default
'') and index ChatMessage.correlation_id for the exit-gate join. Backward:
drop the field and the index. No backfill — pre-existing proposals keep the
3-hop idempotency_key join.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0015_chatthreadgrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatactionproposal",
            name="correlation_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["correlation_id"], name="aichat_msg_correlation_idx"
            ),
        ),
    ]
