# Generated by Django 5.2.16 on 2026-08-11 23:48
"""S38 compaction watermark (additive, reversible).

Forward: add ChatThread.summary_through_sequence (default 0 = nothing
summarized). Backward: drop the field. ChatThread.summary itself has existed
since 0001 and needs no change.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0016_proposal_correlation"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatthread",
            name="summary_through_sequence",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
