# Generated by Django 5.2.16 on 2026-08-15 00:58
"""R0 attachment-RAG registry tables + pgvector extension (dark-safe)."""

import django.db.models.deletion
from django.db import migrations, models

import pgvector.django.vector


def _create_vector_extension(apps, schema_editor):
    """Require pgvector on PostgreSQL; other vendors (sqlite tests) skip."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    try:
        schema_editor.execute('CREATE EXTENSION IF NOT EXISTS vector')
    except Exception as exc:  # pragma: no cover - environment-specific
        raise RuntimeError(
            'The pgvector extension is unavailable on this PostgreSQL server. '
            'Azure Flexible Server: add VECTOR to the azure.extensions server '
            'parameter (R0 ops prerequisite). Local devcontainer: rebuild the '
            'db service with the pgvector/pgvector:pg15 image.'
        ) from exc


class Migration(migrations.Migration):
    """Create AttachmentIngest/AttachmentChunk/MediaSegment and the vector extension."""

    dependencies = [('aichat', '0017_thread_summary_watermark')]

    operations = [
        migrations.RunPython(
            _create_vector_extension, migrations.RunPython.noop, elidable=False
        ),
        migrations.CreateModel(
            name='AttachmentIngest',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('attachment_id', models.PositiveIntegerField(db_index=True)),
                ('model_type', models.CharField(max_length=100)),
                ('model_id', models.PositiveIntegerField()),
                ('client_codes', models.JSONField(blank=True, default=list)),
                ('source_sha256', models.CharField(max_length=64)),
                (
                    'pipeline',
                    models.CharField(
                        choices=[
                            ('doc', 'Document'),
                            ('image', 'Image'),
                            ('video', 'Video'),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('extracting', 'Extracting'),
                            ('embedding', 'Embedding'),
                            ('indexed', 'Indexed'),
                            ('failed', 'Failed'),
                            ('superseded', 'Superseded'),
                            ('deleted', 'Deleted'),
                        ],
                        db_index=True,
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                (
                    'embedding_model',
                    models.CharField(blank=True, default='', max_length=128),
                ),
                ('embedding_dimensions', models.PositiveIntegerField(default=0)),
                (
                    'search_index_name',
                    models.CharField(blank=True, default='', max_length=128),
                ),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'promoted_controlled_document',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='promoted_from_ingests',
                        to='aichat.controlleddocument',
                    ),
                ),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='AttachmentChunk',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                (
                    'section_path',
                    models.CharField(blank=True, default='', max_length=512),
                ),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                (
                    'embedding',
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    'search_doc_id',
                    models.CharField(blank=True, default='', max_length=256),
                ),
                (
                    'ingest',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chunks',
                        to='aichat.attachmentingest',
                    ),
                ),
            ],
            options={'ordering': ['ingest', 'chunk_index']},
        ),
        migrations.CreateModel(
            name='MediaSegment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'media_type',
                    models.CharField(
                        choices=[
                            ('image', 'Image'),
                            ('video_segment', 'Video segment'),
                        ],
                        max_length=16,
                    ),
                ),
                ('segment_index', models.PositiveIntegerField(default=0)),
                ('timecode_start_s', models.FloatField(blank=True, null=True)),
                ('timecode_end_s', models.FloatField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='')),
                (
                    'thumbnail_path',
                    models.CharField(blank=True, default='', max_length=512),
                ),
                (
                    'embedding',
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=3072, null=True
                    ),
                ),
                (
                    'search_doc_id',
                    models.CharField(blank=True, default='', max_length=256),
                ),
                (
                    'ingest',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='segments',
                        to='aichat.attachmentingest',
                    ),
                ),
            ],
            options={'ordering': ['ingest', 'segment_index']},
        ),
        migrations.AddIndex(
            model_name='attachmentingest',
            index=models.Index(
                fields=['model_type', 'model_id'], name='aichat_att_ingest_owner_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='attachmentingest',
            constraint=models.UniqueConstraint(
                fields=('attachment_id', 'source_sha256'),
                name='aichat_att_ingest_sha_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='attachmentingest',
            constraint=models.CheckConstraint(
                condition=models.Q(('source_sha256', ''), _negated=True),
                name='aichat_att_ingest_sha_not_empty',
            ),
        ),
        migrations.AddConstraint(
            model_name='attachmentchunk',
            constraint=models.UniqueConstraint(
                fields=('ingest', 'chunk_index'), name='aichat_att_chunk_idx_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='mediasegment',
            constraint=models.UniqueConstraint(
                fields=('ingest', 'segment_index'), name='aichat_media_seg_idx_uniq'
            ),
        ),
    ]
