"""S5 shadow telemetry: analysis-scope columns on RetrievalMiss (additive)."""

# Generated by Django 5.2.16 on 2026-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add scope_hash/scope_mode/scope_enforced/out_of_scope_hits (dark-safe defaults)."""

    dependencies = [
        ("aichat", "0024_thread_analysis_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="retrievalmiss",
            name="out_of_scope_hits",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="retrievalmiss",
            name="scope_enforced",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="retrievalmiss",
            name="scope_hash",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="retrievalmiss",
            name="scope_mode",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=32
            ),
        ),
    ]
