"""S12 Migration 4: durable quota policy/assignment/reservation/audit models."""

# Generated by Django 5.2.16 on 2026-08-27 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Additive: four new tables + the dedicated quota management permissions."""

    dependencies = [
        ("aichat", "0025_retrievalmiss_scope_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQuotaPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("evaluation", "Evaluation"),
                            ("service", "Service"),
                        ],
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("user_daily_tokens", models.PositiveBigIntegerField()),
                ("tenant_daily_tokens", models.PositiveBigIntegerField()),
                ("deployment_daily_tokens", models.PositiveBigIntegerField()),
                ("requests_per_minute", models.PositiveIntegerField()),
                ("requests_per_hour", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("assign_quota_policy", "Can assign AI quota policies to users"),
                    ("view_quota_reports", "Can view AI quota operational reports"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIQuotaAuditEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("assigned", "Policy assigned"),
                            ("revoked", "Assignment revoked"),
                            ("policy_created", "Policy created"),
                            ("policy_deactivated", "Policy deactivated"),
                        ],
                        max_length=32,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="aichat.aiquotapolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIQuotaAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quota_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="aichat.aiquotapolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIQuotaReservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("policy_version", models.PositiveIntegerField(default=0)),
                ("purpose", models.CharField(blank=True, default="", max_length=64)),
                ("reserved_tokens", models.PositiveBigIntegerField(default=0)),
                (
                    "settled_tokens",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("settled", "Settled"),
                            ("expired", "Expired"),
                        ],
                        default="reserved",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="aiquotapolicy",
            constraint=models.UniqueConstraint(
                fields=("profile", "version"), name="aichat_quota_policy_ver_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="aiquotaassignment",
            index=models.Index(
                fields=["user", "expires_at"], name="aichat_aiqu_user_id_b94251_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiquotareservation",
            index=models.Index(
                fields=["state", "expires_at"], name="aichat_aiqu_state_e70281_idx"
            ),
        ),
    ]
