# Generated by Django 5.2.16 on 2026-08-27 22:00
"""Migration 3 (S10): durable evidence sets for evidence-analysis answers.

Two brand-new tables — ``ChatEvidenceSet`` (one row per aggregate/population
claim's evidence, pk = the opaque ``set_...`` handle) and
``ChatEvidenceSetMember`` (one reference row per evaluated operand, no
source text). New tables are dark-safe on the shared postgres: older code
never reads or writes them, so no ``db_default`` dance is needed (that rule
applies to new columns on existing tables). Rows are written only inside
``ThreadRepository.terminal()``'s transaction and cascade-delete with the
thread → turn chain, satisfying the immediate content-purge rule.
"""

import django.db.models.deletion
from django.db import migrations, models

import aichat.models


class Migration(migrations.Migration):
    """Create ChatEvidenceSet and ChatEvidenceSetMember (aichat 0027)."""

    dependencies = [
        ("aichat", "0026_quota_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatEvidenceSet",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=aichat.models.generate_evidence_set_id,
                        editable=False,
                        max_length=80,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "authorization_scope_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "analysis_scope_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("source_class", models.CharField(max_length=64)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("population_count", models.PositiveIntegerField()),
                ("evaluated_count", models.PositiveIntegerField()),
                ("displayed_count", models.PositiveIntegerField(default=0)),
                ("complete_population", models.BooleanField()),
                ("high_watermarks", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("supports_expansion", models.BooleanField(default=False)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("member_cap", models.PositiveIntegerField(default=25000)),
                ("calculation", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_sets",
                        to="aichat.chatturn",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatEvidenceSetMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("source_class", models.CharField(max_length=64)),
                ("source_object_id", models.CharField(max_length=64)),
                (
                    "source_version",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="aichat.chatevidenceset",
                    ),
                ),
            ],
            options={
                "ordering": ["ordinal"],
            },
        ),
        migrations.AddIndex(
            model_name="chatevidenceset",
            index=models.Index(fields=["turn"], name="aichat_evset_turn_idx"),
        ),
        migrations.AddIndex(
            model_name="chatevidenceset",
            index=models.Index(fields=["source_class"], name="aichat_evset_class_idx"),
        ),
        migrations.AddIndex(
            model_name="chatevidenceset",
            index=models.Index(fields=["snapshot_hash"], name="aichat_evset_snap_idx"),
        ),
        migrations.AddConstraint(
            model_name="chatevidenceset",
            constraint=models.CheckConstraint(
                condition=models.Q(("member_count__lte", models.F("member_cap"))),
                name="aichat_evset_members_within_cap",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatevidenceset",
            constraint=models.CheckConstraint(
                condition=models.Q(("member_cap__lte", 25000)),
                name="aichat_evset_cap_within_envelope",
            ),
        ),
        migrations.AddIndex(
            model_name="chatevidencesetmember",
            index=models.Index(
                fields=["source_class", "source_object_id"],
                name="aichat_evidence_member_src_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatevidencesetmember",
            constraint=models.UniqueConstraint(
                fields=("set", "ordinal"), name="aichat_evidence_member_ordinal_uniq"
            ),
        ),
    ]
