# Generated by Django 5.2.16 on 2026-08-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0027_evidence_sets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPilotStopLatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            (
                                "population_disclosure",
                                "Cross-scope or incomplete population disclosure",
                            ),
                            (
                                "unsafe_procedural_content",
                                "Unsafe uncited procedural content",
                            ),
                            (
                                "unauthorized_effect",
                                "Unauthorized effect or rail bypass",
                            ),
                            ("fabricated_live_state", "Fabricated current-state claim"),
                            (
                                "stale_domain_contamination",
                                "Stale-domain contamination",
                            ),
                            (
                                "eval_fixture_leak",
                                "Eval fixture returned to a non-eval principal",
                            ),
                            (
                                "enforce_fail_open",
                                "Enforce-mode limiter store failed open",
                            ),
                            (
                                "model_pin_mismatch",
                                "Model identity mismatch in a frozen window",
                            ),
                            ("manual", "Owner judgment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=16)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                (
                    "engaged_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("engineering", "Engineering owner"),
                            ("product", "Product owner"),
                            ("maintenance_safety", "Maintenance/safety authority"),
                            ("document_control", "Document-control/data owner"),
                            ("security_privacy", "Security/privacy owner"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("engaged_at", models.DateTimeField(auto_now_add=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "engaged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-engaged_at"],
                "permissions": [
                    ("manage_pilot_stop", "Can set or clear the AI pilot stop latch")
                ],
            },
        ),
        migrations.CreateModel(
            name="AIPilotStopApproval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering owner"),
                            ("product", "Product owner"),
                            ("maintenance_safety", "Maintenance/safety authority"),
                            ("document_control", "Document-control/data owner"),
                            ("security_privacy", "Security/privacy owner"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "latch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="aichat.aipilotstoplatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIRequestRejection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="aipilotstoplatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("active",),
                name="aichat_pilot_latch_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="aipilotstoplatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("active", True), ("cleared_at__isnull", True)),
                    models.Q(("active", False), ("cleared_at__isnull", False)),
                    _connector="OR",
                ),
                name="aichat_pilot_latch_cleared_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="aipilotstopapproval",
            constraint=models.UniqueConstraint(
                fields=("latch", "role"), name="aichat_pilot_approval_role_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="airequestrejection",
            index=models.Index(
                fields=["code", "created_at"], name="aichat_rejection_code_idx"
            ),
        ),
    ]
