# Generated by Django 5.2.16 on 2026-08-28 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0028_pilot_stop_latch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRetentionOutbox",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("reference", models.CharField(max_length=255)),
                ("state", models.CharField(default="pending", max_length=16)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField()),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIUsageMonthlyAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("source", models.CharField(max_length=32)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("dimension", models.CharField(blank=True, default="", max_length=64)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("cached_input_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_tokens", models.PositiveBigIntegerField(default=0)),
                ("reserved_tokens", models.PositiveBigIntegerField(default=0)),
                ("settled_tokens", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatThreadGrantTombstone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access", models.CharField(max_length=16)),
                ("granted_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatThreadTombstone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thread_id", models.CharField(max_length=80, unique=True)),
                ("namespace", models.CharField(max_length=16)),
                ("scope_hash", models.CharField(max_length=64)),
                ("thread_created_at", models.DateTimeField()),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=32)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("had_grants", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name="aiquotaauditevent",
            index=models.Index(
                fields=["created_at"], name="aichat_quota_audit_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airetentionoutbox",
            index=models.Index(
                fields=["state", "next_attempt_at"], name="aichat_outbox_claim_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="airetentionoutbox",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "pending")),
                fields=("kind", "reference"),
                name="aichat_outbox_pending_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagemonthlyaggregate",
            index=models.Index(fields=["month"], name="aichat_usage_agg_month_idx"),
        ),
        migrations.AddConstraint(
            model_name="aiusagemonthlyaggregate",
            constraint=models.UniqueConstraint(
                fields=("month", "source", "user_id", "dimension"),
                name="aichat_usage_agg_uniq",
            ),
        ),
        migrations.AddField(
            model_name="chatthreadgranttombstone",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatthreadgranttombstone",
            name="grantee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatthreadtombstone",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatthreadtombstone",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatthreadgranttombstone",
            name="tombstone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="aichat.chatthreadtombstone",
            ),
        ),
        migrations.AddIndex(
            model_name="chatthreadtombstone",
            index=models.Index(fields=["deleted_at"], name="aichat_tombstone_time_idx"),
        ),
    ]
