# Generated by Django 5.2.16 on 2026-08-29 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0029_retention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlledDocumentApplicability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_content_sha256", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("exact_machine", "Exact machine"),
                            ("inverter_model", "Inverter model"),
                            ("firmware_config", "Firmware / configuration"),
                            ("fleet_wide", "Fleet-wide"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_machine_id", models.PositiveIntegerField(default=0)),
                (
                    "target_serial",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("target_config", models.JSONField(blank=True, default=dict)),
                ("proposal_basis", models.TextField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("countersigned_at", models.DateTimeField(blank=True, null=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("verified", "Verified"),
                            ("revoked", "Revoked"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("revoke_reason", models.TextField(blank=True, default="")),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "countersigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_countersigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_claims",
                        to="aichat.controlleddocument",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="aichat.controlleddocumentapplicability",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicability_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "verify_document_applicability",
                        "Can verify document applicability claims",
                    ),
                    (
                        "countersign_document_applicability",
                        "Can engineering-countersign model/configuration applicability",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["target_machine_id", "state"],
                        name="aichat_docappl_machine_idx",
                    ),
                    models.Index(
                        fields=["target_serial", "state"],
                        name="aichat_docappl_serial_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "verified")),
                        fields=(
                            "document",
                            "kind",
                            "target_machine_id",
                            "target_serial",
                            "target_model",
                        ),
                        name="aichat_docappl_live_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "exact_machine"), _negated=True),
                            models.Q(
                                ("target_machine_id__gt", 0), ("target_model", "")
                            ),
                            _connector="OR",
                        ),
                        name="aichat_docappl_machine_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind__in", ["inverter_model", "firmware_config"]),
                                _negated=True,
                            ),
                            models.Q(
                                models.Q(("target_model", ""), _negated=True),
                                ("target_machine_id", 0),
                            ),
                            _connector="OR",
                        ),
                        name="aichat_docappl_model_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "fleet_wide"), _negated=True),
                            models.Q(
                                ("target_machine_id", 0),
                                ("target_model", ""),
                                ("target_serial", ""),
                            ),
                            _connector="OR",
                        ),
                        name="aichat_docappl_fleet_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("verified_by__isnull", True),
                            models.Q(
                                ("verified_by", models.F("proposed_by")), _negated=True
                            ),
                            _connector="OR",
                        ),
                        name="aichat_docappl_two_party",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "verified"), _negated=True),
                            models.Q(
                                ("verified_by__isnull", False),
                                ("verified_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="aichat_docappl_verified_rec",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("state", "verified"),
                                ("kind__in", ["inverter_model", "firmware_config"]),
                                _negated=True,
                            ),
                            ("countersigned_by__isnull", False),
                            _connector="OR",
                        ),
                        name="aichat_docappl_countersign",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "revoked"), _negated=True),
                            ("revoked_at__isnull", False),
                            _connector="OR",
                        ),
                        name="aichat_docappl_revoked_rec",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("document_content_sha256", ""), _negated=True
                        ),
                        name="aichat_docappl_sha_not_empty",
                    ),
                ],
            },
        ),
    ]
