"""R5 rebuildability: heading/profile/timestamp columns (additive, dark-safe).

Every column carries ``db_default`` or is nullable on purpose: the PostgreSQL
server is shared by aimms-experimental and aimms-dev, so the *other* app runs
the previous revision during the dark window and must keep inserting rows.
Django's AddField applies a plain ``default`` during the ALTER and then drops
the DB default, which would fail those inserts.
"""

# Generated by Django 5.2.16 on 2026-08-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add AttachmentChunk.heading_1..3 and the AttachmentIngest R5 stamps."""

    dependencies = [('aichat', '0030_controlleddocumentapplicability')]

    operations = [
        migrations.AddField(
            model_name='attachmentchunk',
            name='heading_1',
            field=models.CharField(
                blank=True, db_default='', default='', max_length=256
            ),
        ),
        migrations.AddField(
            model_name='attachmentchunk',
            name='heading_2',
            field=models.CharField(
                blank=True, db_default='', default='', max_length=256
            ),
        ),
        migrations.AddField(
            model_name='attachmentchunk',
            name='heading_3',
            field=models.CharField(
                blank=True, db_default='', default='', max_length=256
            ),
        ),
        migrations.AddField(
            model_name='attachmentingest',
            name='embedding_profile',
            field=models.CharField(
                blank=True, db_default='v1', default='v1', max_length=32
            ),
        ),
        migrations.AddField(
            model_name='attachmentingest',
            name='indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentingest',
            name='media_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
