# Generated by Django 5.2.17 on 2026-09-12 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0035_chatactionproposal_preview_hash"),
        ("approvals", "0006_review_and_execution_evidence"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectedMailbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("smtp_imap", "smtp_imap"),
                            ("graph", "graph"),
                            ("google", "google"),
                            ("recording", "recording"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.EmailField(max_length=254)),
                ("aliases", models.JSONField(default=list)),
                ("options", models.JSONField(default=dict)),
                ("encrypted_credentials", models.TextField(blank=True, editable=False)),
                ("binding_version", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=False)),
                ("send_enabled", models.BooleanField(default=False)),
                ("receive_enabled", models.BooleanField(default=False)),
                ("verified_send_at", models.DateTimeField(blank=True, null=True)),
                ("verified_receive_at", models.DateTimeField(blank=True, null=True)),
                ("recipient_allowlist", models.JSONField(default=list, null=True)),
                ("signature", models.TextField(blank=True)),
                ("retention_days", models.PositiveIntegerField(default=30)),
                ("backfill_days", models.PositiveIntegerField(default=30)),
                ("recovery_days", models.PositiveIntegerField(default=90)),
                ("health", models.CharField(default="setup_required", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=150)),
                ("digest", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField()),
                ("content", models.BinaryField()),
                ("scan_state", models.CharField(default="quarantined", max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aichat.connectedmailbox",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aichat.connectedmailbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailDraft",
            fields=[
                (
                    "approval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="email_draft",
                        serialize=False,
                        to="approvals.approval",
                    ),
                ),
                ("binding_version", models.PositiveIntegerField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("envelope", models.JSONField(default=list)),
                ("sender", models.EmailField(max_length=254)),
                ("rfc_message_id", models.CharField(max_length=255)),
                ("raw", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aichat.connectedmailbox",
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True, related_name="drafts", to="aichat.mailattachment"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identity_hash", models.CharField(max_length=64)),
                ("provider_identity", models.TextField()),
                ("rfc_message_id", models.CharField(blank=True, max_length=998)),
                ("in_reply_to", models.TextField(blank=True)),
                ("references", models.JSONField(default=list)),
                ("sender", models.JSONField(default=list)),
                ("to", models.JSONField(default=list)),
                ("cc", models.JSONField(default=list)),
                ("reply_to", models.JSONField(default=list)),
                ("subject", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("raw", models.BinaryField(default=bytes)),
                ("content_hash", models.CharField(max_length=64)),
                ("provider_date", models.DateTimeField(null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("direction", models.CharField(default="inbound", max_length=10)),
                ("processed", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("expired", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aichat.connectedmailbox",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aichat.mailconversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection", models.CharField(max_length=255)),
                ("location_hash", models.CharField(max_length=64)),
                ("provider_location", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("removed", models.BooleanField(default=False)),
                ("generation", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aichat.connectedmailbox",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="aichat.mailmessage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mailattachment",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="aichat.mailmessage",
            ),
        ),
        migrations.CreateModel(
            name="MailReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("outcome", models.CharField(max_length=25)),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="aichat.connectedmailbox",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mail_receipts",
                        to="approvals.approvalexecution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailSyncState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection", models.CharField(max_length=255)),
                ("scope_version", models.PositiveIntegerField(default=1)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("continuation", models.JSONField(null=True)),
                ("checkpoint", models.JSONField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("last_success", models.DateTimeField(null=True)),
                ("coverage_start", models.DateTimeField(null=True)),
                ("status", models.CharField(default="catching_up", max_length=25)),
                ("has_gap", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, max_length=60)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_states",
                        to="aichat.connectedmailbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailboxGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_read", models.BooleanField(default=False)),
                ("can_draft", models.BooleanField(default=False)),
                ("can_send", models.BooleanField(default=False)),
                ("can_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="aichat.connectedmailbox",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("group__isnull", True), ("user__isnull", False)),
                            models.Q(("group__isnull", False), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="mailbox_grant_one_subject",
                    ),
                    models.UniqueConstraint(
                        fields=("account", "user"), name="mailbox_grant_user"
                    ),
                    models.UniqueConstraint(
                        fields=("account", "group"), name="mailbox_grant_group"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mailmessage",
            constraint=models.UniqueConstraint(
                fields=("account", "identity_hash"),
                name="mail_message_account_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="maillocation",
            constraint=models.UniqueConstraint(
                fields=("account", "collection", "location_hash"),
                name="mail_location_account_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailsyncstate",
            constraint=models.UniqueConstraint(
                fields=("account", "collection"), name="mail_sync_account_collection"
            ),
        ),
    ]
