# Generated by Django 5.2.17 on 2026-09-12 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aichat", "0036_connectedmailbox_mailattachment_mailconversation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="connectedmailbox",
            name="oauth_refresh_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MailboxOAuthAttempt",
            fields=[
                (
                    "state_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("binding_version", models.PositiveIntegerField()),
                ("encrypted_verifier", models.TextField(editable=False)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aichat.connectedmailbox",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
