# Generated by Django 5.2.17 on 2026-09-13 20:05

"""Additive governed-stock schema; no historical receipts are inferred."""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the Phase E governed voice contract without changing old evidence."""
    dependencies = [
        ('aichat', '0037_connectedmailbox_oauth_refresh_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatactionproposal',
            name='target_stock_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatactionproposal',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('work_order.hold', 'Hold work order'),
                    ('work_order.resume', 'Resume work order'),
                    ('work_order.schedule', 'Schedule work order'),
                    ('work_order.resize', 'Resize work order'),
                    ('work_order.update', 'Update work order plan'),
                    ('work_order.assign', 'Assign work order'),
                    ('work_order.delete', 'Delete work order'),
                    ('work_order.cancel', 'Cancel work order'),
                    ('work_order.transition', 'Transition work order lifecycle'),
                    ('work_order.create', 'Create work order'),
                    ('work_order.create_child', 'Create child work order'),
                    ('repair_work_package.create', 'Create repair work package'),
                    ('work_order.generate_procurement', 'Generate procurement child'),
                    ('dependency.create', 'Create dependency'),
                    ('dependency.delete', 'Delete dependency'),
                    ('schedule.optimize', 'Optimize schedule (bulk)'),
                    ('stock.add', 'Add stock'),
                    ('stock.remove', 'Remove stock'),
                    ('stock.transfer', 'Transfer stock'),
                    ('stock.count', 'Count stock'),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name='StockCommandReceipt',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('action', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('receipt', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('actor', 'idempotency_key'),
                        name='aichat_stock_command_key',
                    )
                ]
            },
        ),
    ]
