# Generated by Django 5.2.17 on 2026-09-13 20:20

"""Additive Phase E schema changes; no historical consent or receipts are inferred."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the Phase E governed voice contract without changing old evidence."""
    dependencies = [('aichat', '0038_governed_stock_commands')]

    operations = [
        migrations.AlterField(
            model_name='chatactionproposal',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('work_order.hold', 'Hold work order'),
                    ('work_order.resume', 'Resume work order'),
                    ('work_order.schedule', 'Schedule work order'),
                    ('work_order.resize', 'Resize work order'),
                    ('work_order.update', 'Update work order plan'),
                    ('work_order.assign', 'Assign work order'),
                    ('work_order.delete', 'Delete work order'),
                    ('work_order.cancel', 'Cancel work order'),
                    ('work_order.transition', 'Transition work order lifecycle'),
                    ('work_order.create', 'Create work order'),
                    ('work_order.create_child', 'Create child work order'),
                    ('repair_work_package.create', 'Create repair work package'),
                    ('work_order.generate_procurement', 'Generate procurement child'),
                    ('dependency.create', 'Create dependency'),
                    ('dependency.delete', 'Delete dependency'),
                    ('schedule.optimize', 'Optimize schedule (bulk)'),
                    ('stock.add', 'Add stock'),
                    ('stock.remove', 'Remove stock'),
                    ('stock.transfer', 'Transfer stock'),
                    ('stock.count', 'Count stock'),
                    ('procedure.complete', 'Complete procedure step'),
                ],
                max_length=32,
            ),
        )
    ]
