# Generated by Django 5.2.15 on 2026-07-18 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_alter_assetmaintenancerecord_work_order"),
        ("company", "0080_company_tags"),
        ("part", "0152_alter_partpricing_currency"),
        ("tasks", "0008_closeoutamendment_closeoutcapture_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartCandidateEvaluation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_revision", models.PositiveIntegerField()),
                ("retrieval_tiers", models.JSONField(blank=True, default=list)),
                ("candidate_snapshot", models.JSONField(default=dict)),
                ("candidate_fingerprint", models.CharField(max_length=71)),
                ("eligible", models.BooleanField(db_index=True, default=False)),
                ("hard_conflicts", models.JSONField(blank=True, default=list)),
                ("matched_attributes", models.JSONField(blank=True, default=list)),
                ("missing_attributes", models.JSONField(blank=True, default=list)),
                ("rank_factors", models.JSONField(blank=True, default=list)),
                ("rank_value", models.IntegerField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("availability_snapshot", models.JSONField(blank=True, default=dict)),
                ("requirements_hash", models.CharField(max_length=71)),
                ("evaluation_hash", models.CharField(max_length=71)),
                ("evaluated_at", models.DateTimeField()),
                ("rejected", models.BooleanField(default=False)),
                ("rejected_reason", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_evaluations",
                        to="part.part",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["session", "session_revision", "rank", "candidate"],
            },
        ),
        migrations.CreateModel(
            name="PartVerificationPolicyVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(help_text="Policy key", max_length=64)),
                (
                    "version",
                    models.PositiveIntegerField(default=1, help_text="Policy version"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("schema_version", models.PositiveIntegerField(default=1)),
                (
                    "definition",
                    models.JSONField(
                        default=dict, help_text="Canonical policy definition document"
                    ),
                ),
                ("definition_hash", models.CharField(blank=True, max_length=71)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "manage_partverificationpolicy",
                        "Can manage part verification policy",
                    )
                ],
                "unique_together": {("key", "version")},
            },
        ),
        migrations.CreateModel(
            name="PartVerificationDecision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_revision", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("no_safe_match", "No Safe Match"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decision_snapshot", models.JSONField(default=dict)),
                ("decision_hash", models.CharField(max_length=71, unique=True)),
                ("requirements_hash", models.CharField(blank=True, max_length=71)),
                ("source_fingerprint", models.CharField(blank=True, max_length=71)),
                ("evaluation_hash", models.CharField(blank=True, max_length=71)),
                ("policy_hash", models.CharField(blank=True, max_length=71)),
                ("scope_fingerprint", models.CharField(blank=True, max_length=71)),
                ("reason", models.TextField()),
                ("decided_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "selected_evaluation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="part.partcandidateevaluation",
                    ),
                ),
                (
                    "selected_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_decisions",
                        to="part.part",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="part.partverificationpolicyversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_at"],
            },
        ),
        migrations.AddField(
            model_name="partcandidateevaluation",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="part.partverificationpolicyversion",
            ),
        ),
        migrations.CreateModel(
            name="PartVerificationSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, unique=True
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("installed_replacement", "Installed Replacement"),
                            ("bom_component", "BOM Component"),
                            ("job_kit_substitution", "Job Kit Substitution"),
                            ("rfq_demand", "RFQ Demand"),
                            ("po_line", "Purchase Order Line"),
                            ("manual", "Manual Verification"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("collecting", "Collecting"),
                            ("evaluating", "Evaluating"),
                            ("review_required", "Review Required"),
                            ("confirmed", "Confirmed"),
                            ("no_safe_match", "No Safe Match"),
                            ("stale", "Stale"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="collecting",
                        max_length=24,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("scope_site_key", models.CharField(blank=True, max_length=100)),
                ("scope_fingerprint", models.CharField(max_length=71)),
                ("requirements_hash", models.CharField(blank=True, max_length=71)),
                ("source_fingerprint", models.CharField(blank=True, max_length=71)),
                ("evaluation_hash", models.CharField(blank=True, max_length=71)),
                ("stale_reason", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("universe_complete", models.BooleanField(default=False)),
                ("considered_count", models.PositiveIntegerField(default=0)),
                ("eligible_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_sessions",
                        to="part.bomitem",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_verification_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="part.partverificationdecision",
                    ),
                ),
                (
                    "job_kit_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_verification_sessions",
                        to="tasks.jobkitline",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_verification_sessions",
                        to="assets.assetmachine",
                    ),
                ),
                (
                    "machine_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_verification_sessions",
                        to="assets.machinepart",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="part.partverificationpolicyversion",
                    ),
                ),
                (
                    "requested_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_sessions",
                        to="part.part",
                    ),
                ),
                (
                    "scope_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_verification_sessions",
                        to="company.company",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_verification_sessions",
                        to="tasks.kanbancard",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "review_partverification",
                        "Can review part verification candidates",
                    ),
                    (
                        "confirm_partverification",
                        "Can confirm part verification decisions",
                    ),
                    (
                        "invalidate_partverification",
                        "Can invalidate part verifications",
                    ),
                    ("use_partverification", "Can bind part verifications to effects"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartVerificationRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "value_kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("identifier", "Identifier"),
                            ("decimal", "Decimal"),
                            ("range", "Range"),
                            ("set", "Set"),
                            ("boolean", "Boolean"),
                            ("revision", "Revision"),
                            ("certification", "Certification"),
                        ],
                        max_length=16,
                    ),
                ),
                ("operator", models.CharField(max_length=32)),
                ("value", models.JSONField(blank=True, null=True)),
                ("raw_value", models.JSONField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=25)),
                ("tolerance", models.JSONField(blank=True, default=dict)),
                ("hard_constraint", models.BooleanField(default=True)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("missing", "Missing"),
                            ("conflicting", "Conflicting"),
                            ("invalid", "Invalid"),
                        ],
                        default="missing",
                        max_length=16,
                    ),
                ),
                ("blocker_code", models.CharField(blank=True, max_length=64)),
                ("authority", models.CharField(blank=True, max_length=64)),
                ("provenance", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="part.partverificationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="PartVerificationEvidence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement_key", models.CharField(blank=True, max_length=100)),
                ("source_kind", models.CharField(max_length=32)),
                ("source_model", models.CharField(blank=True, max_length=100)),
                ("source_object_id", models.CharField(blank=True, max_length=36)),
                ("source_field", models.CharField(blank=True, max_length=100)),
                ("source_version", models.CharField(blank=True, max_length=100)),
                ("source_fingerprint", models.CharField(blank=True, max_length=71)),
                ("digest", models.CharField(blank=True, max_length=71)),
                ("raw_value", models.JSONField(blank=True, null=True)),
                ("canonical_value", models.JSONField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=25)),
                ("authority", models.CharField(blank=True, max_length=64)),
                ("origin", models.CharField(default="system", max_length=32)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="part.partverificationevidence",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="part.partverificationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="PartVerificationEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session_created", "Session Created"),
                            ("evidence_attached", "Evidence Attached"),
                            ("evidence_decided", "Evidence Decided"),
                            ("session_evaluated", "Session Evaluated"),
                            ("evaluation_blocked", "Evaluation Blocked"),
                            ("candidate_rejected", "Candidate Rejected"),
                            ("session_confirmed", "Session Confirmed"),
                            ("no_safe_match_recorded", "No Safe Match Recorded"),
                            ("session_stale", "Session Stale"),
                            ("session_reevaluated", "Session Reevaluated"),
                            ("session_cancelled", "Session Cancelled"),
                            ("use_bound", "Use Bound"),
                        ],
                        max_length=32,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=24)),
                ("reason", models.CharField(blank=True, max_length=64)),
                ("correlation_id", models.CharField(blank=True, max_length=36)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="part.partverificationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="partverificationdecision",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decisions",
                to="part.partverificationsession",
            ),
        ),
        migrations.CreateModel(
            name="PartVerificationCommand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=64)),
                ("scope_fingerprint", models.CharField(blank=True, max_length=71)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=71)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="part.partverificationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="partcandidateevaluation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_evaluations",
                to="part.partverificationsession",
            ),
        ),
        migrations.CreateModel(
            name="PartVerificationUse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer_kind", models.CharField(max_length=32)),
                ("consumer_model", models.CharField(blank=True, max_length=100)),
                ("consumer_object_id", models.CharField(blank=True, max_length=36)),
                ("consumer_action", models.CharField(max_length=64)),
                ("scope_fingerprint", models.CharField(blank=True, max_length=71)),
                ("final_observation_hash", models.CharField(blank=True, max_length=71)),
                ("command_hash", models.CharField(blank=True, max_length=71)),
                ("idempotency_key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uses",
                        to="part.partverificationdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddIndex(
            model_name="partverificationsession",
            index=models.Index(
                fields=["state", "purpose"], name="part_partve_state_295786_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partverificationsession",
            index=models.Index(
                fields=["scope_customer", "state"],
                name="part_partve_scope_c_496df6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partverificationsession",
            index=models.Index(
                fields=["expires_at"], name="part_partve_expires_bc5336_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partverificationrequirement",
            unique_together={("session", "key")},
        ),
        migrations.AddIndex(
            model_name="partverificationevidence",
            index=models.Index(
                fields=["session", "requirement_key"],
                name="part_partve_session_ebb498_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="partverificationevent",
            index=models.Index(
                fields=["session", "event_type"], name="part_partve_session_c34bfb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partverificationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "confirmed"),
                        ("selected_evaluation__isnull", False),
                        ("selected_part__isnull", False),
                    ),
                    models.Q(
                        ("kind", "no_safe_match"),
                        ("selected_evaluation__isnull", True),
                        ("selected_part__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="rpf_decision_kind_selection_invariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partverificationcommand",
            unique_together={("command", "idempotency_key")},
        ),
        migrations.AddConstraint(
            model_name="partcandidateevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eligible", True), ("rank__isnull", True), _connector="OR"
                ),
                name="rpf_ineligible_candidate_has_no_rank",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partcandidateevaluation",
            unique_together={("session", "session_revision", "candidate")},
        ),
        migrations.AlterUniqueTogether(
            name="partverificationuse",
            unique_together={("consumer_kind", "consumer_action", "idempotency_key")},
        ),
    ]
