# Generated by Django 5.2.15 on 2026-07-29 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_remove_assetmachine_customer"),
        ("part", "0153_partcandidateevaluation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partverificationsession",
            name="scope_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="part_verification_sessions",
                to="assets.client",
            ),
        ),
    ]
