# Generated by Django 5.2.16 on 2026-08-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0154_partverificationsession_scope_client"),
        ("tasks", "0030_workorder_tasks_wo_actual_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partverificationsession",
            name="work_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="part_verification_sessions",
                to="tasks.workorder",
            ),
        ),
    ]
