# Generated by Django 5.2.17 on 2026-09-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0154_remove_part_notes"),
        ("part", "0155_alter_partverificationsession_work_order"),
    ]

    operations = []
