"""Auto-generated database migration."""

# Generated by Django 5.2.15 on 2026-07-15 05:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("thread_id", models.CharField(max_length=255)),
                ("scope_key", models.CharField(max_length=255)),
                ("scope_hash", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("connecting", "Connecting"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="created",
                        max_length=16,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("webrtc", "WebRTC (public preview)"),
                            ("relay", "Server WebSocket relay"),
                        ],
                        max_length=16,
                    ),
                ),
                ("azure_session_id", models.CharField(blank=True, max_length=128)),
                ("policy_version", models.CharField(max_length=64)),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("terminal_reason", models.CharField(blank=True, max_length=64)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceTransportAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("webrtc", "WebRTC (public preview)"),
                            ("relay", "Server WebSocket relay"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("connected", "Connected"),
                            ("failed", "Failed"),
                            ("closed", "Closed"),
                        ],
                        default="started",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_attempts",
                        to="voice.voicesession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceUtterance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("turn_id", models.CharField(blank=True, max_length=64)),
                (
                    "utterance_type",
                    models.CharField(
                        choices=[
                            ("interim_status", "Interim status"),
                            ("completed_answer", "Completed answer"),
                            ("failure_status", "Failure status"),
                        ],
                        max_length=20,
                    ),
                ),
                ("spoken_summary", models.TextField()),
                ("spoken_summary_hash", models.CharField(max_length=64)),
                ("response_id", models.CharField(blank=True, max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                (
                    "playback_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requested", "Requested"),
                            ("playing", "Playing"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utterances",
                        to="voice.voicesession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(
                fields=["owner", "state"], name="voice_session_owner_state"
            ),
        ),
        migrations.AddIndex(
            model_name="voicesession",
            index=models.Index(
                fields=["state", "last_activity_at"], name="voice_session_sweep_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voicesession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state__in", ["ended", "failed", "expired"]),
                        ("ended_at__isnull", False),
                    ),
                    models.Q(
                        ("state__in", ["ended", "failed", "expired"]), _negated=True
                    ),
                    _connector="OR",
                ),
                name="voice_session_terminal_has_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="voicesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_hash", ""), _negated=True),
                name="voice_session_scope_required",
            ),
        ),
        migrations.AddIndex(
            model_name="voicetransportattempt",
            index=models.Index(
                fields=["session", "created_at"], name="voice_attempt_session_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceutterance",
            index=models.Index(
                fields=["session", "utterance_type"], name="voice_utterance_session_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceutterance",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("utterance_type", "completed_answer"),
                    models.Q(("response_id", ""), _negated=True),
                ),
                fields=("session", "response_id"),
                name="voice_utterance_one_answer",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceutterance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("spoken_summary", ""), _negated=True),
                    models.Q(("spoken_summary_hash", ""), _negated=True),
                ),
                name="voice_utterance_text_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceutterance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("utterance_type", "completed_answer"),
                    ("response_id", ""),
                    _connector="OR",
                ),
                name="voice_utterance_answer_binds_response",
            ),
        ),
    ]
