"""Auto-generated database migration."""

# Generated by Django 5.2.15 on 2026-07-15 18:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration."""
    dependencies = [
        ("voice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceCaptureSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope_key", models.CharField(max_length=255)),
                ("scope_hash", models.CharField(max_length=64)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("fault_intake", "Fault intake"),
                            ("closeout", "Closeout"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_work_order_id", models.PositiveIntegerField()),
                ("target_version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("review", "Review required"),
                            ("accepted", "Accepted"),
                            ("committed", "Committed"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("consent_version", models.CharField(max_length=32)),
                ("consented_at", models.DateTimeField()),
                ("policy_version", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("terminal_reason", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voice_captures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceTranscriptRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("full_text", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("segments", models.JSONField(blank=True, default=list)),
                ("language", models.CharField(default="en-US", max_length=16)),
                (
                    "provider",
                    models.CharField(default="voice_live_realtime", max_length=32),
                ),
                ("edit_reason", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="voice.voicecapturesession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="voice.voicetranscriptrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["revision"],
            },
        ),
        migrations.CreateModel(
            name="VoiceTranscriptAcceptance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_hash", models.CharField(max_length=64)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptance",
                        to="voice.voicetranscriptrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["accepted_at"],
            },
        ),
        migrations.AddField(
            model_name="voicecapturesession",
            name="accepted_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="voice.voicetranscriptrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="voicetranscriptrevision",
            constraint=models.UniqueConstraint(
                fields=("capture", "revision"), name="voice_revision_monotonic"
            ),
        ),
        migrations.AddConstraint(
            model_name="voicetranscriptrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("full_text", ""), _negated=True),
                    models.Q(("content_hash", ""), _negated=True),
                ),
                name="voice_revision_text_required",
            ),
        ),
        migrations.AddIndex(
            model_name="voicecapturesession",
            index=models.Index(
                fields=["owner", "purpose", "state"], name="voice_capture_owner_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voicecapturesession",
            constraint=models.UniqueConstraint(
                fields=("owner", "idempotency_key"), name="voice_capture_intent_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="voicecapturesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("consent_version", ""), _negated=True),
                name="voice_capture_consent_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="voicecapturesession",
            constraint=models.CheckConstraint(
                condition=models.Q(("scope_hash", ""), _negated=True),
                name="voice_capture_scope_required",
            ),
        ),
    ]
