# Generated by Django 5.2.16 on 2026-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0002_voicecapturesession_voicetranscriptrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicesession",
            name="analysis_scope_version",
            field=models.PositiveBigIntegerField(db_default=0, default=0),
        ),
    ]
