# Generated by Django 5.2.16 on 2026-09-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voice", "0003_voicesession_analysis_scope_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiceutterance",
            name="utterance_type",
            field=models.CharField(
                choices=[
                    ("interim_status", "Interim status"),
                    ("completed_answer", "Completed answer"),
                    ("failure_status", "Failure status"),
                    ("prompt", "Prompt"),
                ],
                max_length=20,
            ),
        ),
    ]
