# Generated by Django 5.2.17 on 2026-09-13 20:43

"""Bind captures to live sessions; never manufacture historical consent."""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the Phase E governed voice contract without changing old evidence."""
    dependencies = [
        ('voice', '0007_voicepresentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecapturesession',
            name='live_session',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='captures',
                to='voice.voicesession',
            ),
        ),
        migrations.AddField(
            model_name='voicetranscriptrevision',
            name='source_turn_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='voicetranscriptrevision',
            constraint=models.UniqueConstraint(
                condition=models.Q(('source_turn_id', ''), _negated=True),
                fields=('capture', 'source_turn_id'),
                name='voice_revision_turn_key',
            ),
        ),
    ]
