# Generated by Django - AI Conversation Persistence

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    """Migration to add AI conversation persistence tables."""

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0039_emailthread_emailmessage'),
    ]

    operations = [
        # Create AIConversationThread table
        migrations.CreateModel(
            name='AIConversationThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('thread_id', models.CharField(db_index=True, help_text='Unique identifier for this conversation thread', max_length=100, unique=True, verbose_name='Thread ID')),
                ('title', models.CharField(blank=True, default='', help_text='Title of the conversation thread', max_length=255, verbose_name='Title')),
                ('summary', models.TextField(blank=True, default='', help_text='AI-generated summary of the conversation', verbose_name='Summary')),
                ('turn_count', models.PositiveIntegerField(default=0, help_text='Number of conversation turns', verbose_name='Turn Count')),
                ('summary_turn', models.PositiveIntegerField(default=0, help_text='Turn count when summary was last updated', verbose_name='Summary Turn')),
                ('last_workflow', models.CharField(blank=True, help_text='ID of the last workflow used', max_length=100, null=True, verbose_name='Last Workflow')),
                ('pending_handoff', models.CharField(blank=True, help_text='Workflow ID for pending handoff', max_length=100, null=True, verbose_name='Pending Handoff')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this thread is active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_threads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI Conversation Thread',
                'verbose_name_plural': 'AI Conversation Threads',
                'ordering': ['-updated_at'],
            },
        ),
        
        # Create AIConversationMessage table
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True, verbose_name='Message ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20, verbose_name='Role')),
                ('content', models.TextField(help_text='Message content', verbose_name='Content')),
                ('workflow_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Workflow ID')),
                ('tool_call_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tool Call ID')),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tool Name')),
                ('message_metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata', verbose_name='Metadata')),
                ('token_count', models.PositiveIntegerField(default=0, help_text='Estimated token count for this message', verbose_name='Token Count')),
                ('is_indexed', models.BooleanField(default=False, help_text='Whether this message is indexed in Azure AI Search', verbose_name='Indexed')),
                ('search_document_id', models.CharField(blank=True, help_text='Document ID in Azure AI Search index', max_length=100, null=True, verbose_name='Search Document ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='common.aiconversationthread', verbose_name='Thread')),
            ],
            options={
                'verbose_name': 'AI Conversation Message',
                'verbose_name_plural': 'AI Conversation Messages',
                'ordering': ['created_at'],
            },
        ),
        
        # Create AISearchIndexStatus table
        migrations.CreateModel(
            name='AISearchIndexStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=100, unique=True, verbose_name='Index Name')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('document_count', models.PositiveIntegerField(default=0, verbose_name='Document Count')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('error', 'Error')], default='idle', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'AI Search Index Status',
                'verbose_name_plural': 'AI Search Index Statuses',
            },
        ),
        
        # Add indexes for efficient queries
        migrations.AddIndex(
            model_name='aiconversationthread',
            index=models.Index(fields=['user', '-updated_at'], name='common_aico_user_id_8f8e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationthread',
            index=models.Index(fields=['is_active', '-updated_at'], name='common_aico_is_acti_6e5f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['thread', 'created_at'], name='common_aico_thread__2a3b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['role', 'created_at'], name='common_aico_role_cr_5d6e7f_idx'),
        ),
    ]
