# Generated by Django 4.2.26 on 2025-12-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0040_ai_conversation_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiconversationmessage",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="aiconversationthread",
            name="user",
        ),
        migrations.DeleteModel(
            name="AISearchIndexStatus",
        ),
        migrations.DeleteModel(
            name="AIConversationMessage",
        ),
        migrations.DeleteModel(
            name="AIConversationThread",
        ),
    ]
