# Generated by Django 5.2.15 on 2026-07-12 22:58
"""Merge migration for divergent common heads."""

from django.db import migrations


class Migration(migrations.Migration):
    """Merge divergent migration branches."""


    dependencies = [
        ("common", "0041_remove_aiconversationmessage_thread_and_more"),
        ("common", "0046_alter_emailmessage_global_id_and_more"),
    ]

    operations = []
