# Generated by Django 5.2.17 on 2026-09-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0049_merge_upstream_sync"),
        ("common", "0052_remove_notesimage_model_id_and_more"),
    ]

    operations = []
