# Generated by Django 5.2.15 on 2026-08-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_ruleset_closeout_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleset",
            name="can_apply_procedure",
            field=models.BooleanField(
                default=False, verbose_name="Can apply procedures to work orders"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_approve_jobkit_substitution",
            field=models.BooleanField(
                default=False, verbose_name="Can approve job kit substitutions"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_assign_workorder",
            field=models.BooleanField(
                default=False, verbose_name="Can assign work orders"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_author_procedure",
            field=models.BooleanField(
                default=False, verbose_name="Can author procedures"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_complete_workorder",
            field=models.BooleanField(
                default=False, verbose_name="Can complete work orders"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_execute_workorder",
            field=models.BooleanField(
                default=False, verbose_name="Can execute work orders"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_issue_jobkit",
            field=models.BooleanField(default=False, verbose_name="Can issue job kits"),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_manage_jobkit",
            field=models.BooleanField(
                default=False, verbose_name="Can manage job kits"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_plan_workorder",
            field=models.BooleanField(
                default=False, verbose_name="Can plan work orders"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_publish_procedure",
            field=models.BooleanField(
                default=False, verbose_name="Can publish procedures"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_reserve_jobkit",
            field=models.BooleanField(
                default=False, verbose_name="Can reserve job kit stock"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_review_procedure",
            field=models.BooleanField(
                default=False, verbose_name="Can review procedures"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_stage_jobkit",
            field=models.BooleanField(default=False, verbose_name="Can stage job kits"),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_transition_workorder",
            field=models.BooleanField(
                default=False, verbose_name="Can transition work orders"
            ),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="can_view_workorder_audit",
            field=models.BooleanField(
                default=False, verbose_name="Can view work order audit surfaces"
            ),
        ),
    ]
