# Generated by Django 5.2.16 on 2026-09-12 17:16
"""Add independent, default-off email permissions to group roles."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Keep old application inserts compatible with database defaults."""

    dependencies = [('users', '0019_approval_review_role')]

    operations = [
        migrations.AlterModelOptions(
            name='ruleset',
            options={
                'permissions': [
                    ('view_email', 'Can read emails and attachments'),
                    ('send_email', 'Can send emails'),
                ]
            },
        ),
        migrations.AddField(
            model_name='ruleset',
            name='can_send_emails',
            field=models.BooleanField(
                db_default=False, default=False, verbose_name='Can send emails'
            ),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='can_view_emails',
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name='Can read emails and attachments',
            ),
        ),
    ]
