# Generated by Django 5.2.17 on 2026-09-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_legacy_user_sessions_table"),
        ("users", "0021_email_role_grants"),
    ]

    operations = []
