# Generated by Django 5.2.17 on 2026-09-13 21:04

"""Expose the existing in-app model grant without granting new privileges."""

from django.db import migrations, models


def preserve_notification_grants(apps, schema_editor):
    """Keep already granted group permissions through future ruleset rebuilds."""
    alias = schema_editor.connection.alias
    groups = apps.get_model("auth", "Group").objects.using(alias).filter(
        permissions__content_type__app_label="common",
        permissions__content_type__model="notificationmessage",
        permissions__codename="add_notificationmessage",
    )
    rules = apps.get_model("users", "RuleSet").objects.using(alias)
    for group in groups.iterator():
        rules.update_or_create(
            group_id=group.pk,
            name="work_order",
            defaults={"can_publish_notifications": True},
        )


class Migration(migrations.Migration):
    """Add an independent administrator checkbox, defaulting to no grant."""

    dependencies = [
        ("users", "0023_sync_ruleset_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleset",
            name="can_publish_notifications",
            field=models.BooleanField(
                db_default=False,
                default=False,
                verbose_name="Can create in-app notifications",
            ),
        ),
        migrations.RunPython(preserve_notification_grants, migrations.RunPython.noop),
    ]
