# Generated by Django 4.2.26 on 2026-03-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In Review"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("denied", "Denied"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "risk_tier",
                    models.SmallIntegerField(
                        default=2,
                        help_text="0-3, higher = more dangerous",
                        verbose_name="Risk Tier",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email", "Send Email"),
                            ("purchase_order", "Create Purchase Order"),
                            ("sales_order", "Create Sales Order"),
                            ("stock_update", "Update Stock"),
                            ("workflow", "Run Workflow"),
                            ("notification", "Send Notification"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Action Type",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Human-readable one-line summary of the proposed action",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Current draft arguments (JSONB)",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "payload_schema_version",
                    models.IntegerField(
                        default=1, verbose_name="Payload Schema Version"
                    ),
                ),
                (
                    "source_chat_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Source Chat ID",
                    ),
                ),
                (
                    "agent_run_id",
                    models.CharField(
                        db_index=True,
                        help_text="Durable workflow instance correlation",
                        max_length=255,
                        verbose_name="Agent Run ID",
                    ),
                ),
                (
                    "agent_checkpoint_id",
                    models.CharField(
                        max_length=255, verbose_name="Agent Checkpoint ID"
                    ),
                ),
                (
                    "tool_call_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identifies approval request in the agent run",
                        max_length=255,
                        verbose_name="Tool Call ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Expires At"
                    ),
                ),
                (
                    "baseline_context",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot for drift detection",
                        verbose_name="Baseline Context",
                    ),
                ),
                (
                    "preconditions",
                    models.JSONField(
                        default=dict,
                        help_text="Machine-check rules",
                        verbose_name="Preconditions",
                    ),
                ),
                (
                    "card_context",
                    models.JSONField(
                        default=dict,
                        help_text="Self-contained bundle for Modify-in-chat",
                        verbose_name="Card Context",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="SHA-256(agent_run_id:tool_call_id)",
                        max_length=64,
                        unique=True,
                        verbose_name="Idempotency Key",
                    ),
                ),
                (
                    "viewed_confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viewed Confirmed At"
                    ),
                ),
                (
                    "current_revision_number",
                    models.IntegerField(
                        default=0,
                        help_text="Denormalized for optimistic concurrency on /revise",
                        verbose_name="Current Revision Number",
                    ),
                ),
                (
                    "modification_lock_acquired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lock Acquired At"
                    ),
                ),
                (
                    "modification_lock_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lock Expires At"
                    ),
                ),
                (
                    "deny_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Deny Reason"
                    ),
                ),
                (
                    "canceled_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Canceled Reason"
                    ),
                ),
                (
                    "execution_result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Execution Result"
                    ),
                ),
                (
                    "execution_error",
                    models.JSONField(
                        blank=True,
                        help_text="Redacted error details",
                        null=True,
                        verbose_name="Execution Error",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "assigned_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "modification_lock_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modification Lock User",
                    ),
                ),
                (
                    "resolved_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
                (
                    "viewed_confirmed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viewed_confirmed_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Viewed Confirmed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval",
                "verbose_name_plural": "Approvals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutedEffect",
            fields=[
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Idempotency Key",
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(max_length=100, verbose_name="Effect Type"),
                ),
                (
                    "effect_ref",
                    models.CharField(
                        help_text="Reference to created object/message",
                        max_length=255,
                        verbose_name="Effect Reference",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executed_effects",
                        to="approvals.approval",
                        verbose_name="Approval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Executed Effect",
                "verbose_name_plural": "Executed Effects",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_number",
                    models.IntegerField(
                        help_text="0 = initial snapshot at creation; 1+ = user revisions",
                        verbose_name="Revision Number",
                    ),
                ),
                ("payload_snapshot", models.JSONField(verbose_name="Payload Snapshot")),
                (
                    "diff_summary",
                    models.JSONField(
                        blank=True,
                        help_text="NULL for revision 0 (initial snapshot at creation)",
                        null=True,
                        verbose_name="Diff Summary",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="approvals.approval",
                        verbose_name="Approval",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for revision 0 (system-generated)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Revision",
                "verbose_name_plural": "Approval Revisions",
                "ordering": ["revision_number"],
                "unique_together": {("approval", "revision_number")},
            },
        ),
        migrations.CreateModel(
            name="ApprovalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("opened", "Opened"),
                            ("viewed_confirmed", "Viewed Confirmed"),
                            ("changes_requested", "Changes Requested"),
                            ("revised", "Revised"),
                            ("superseded", "Superseded"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                            ("cancel_reverted", "Cancel Reverted"),
                            ("revalidation_failed", "Revalidation Failed"),
                            ("resume_failed", "Resume Failed"),
                            ("execution_callback", "Execution Callback"),
                            ("lock_acquired", "Lock Acquired"),
                            ("lock_released", "Lock Released"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "event_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Diffs, reasons, errors, metadata",
                        verbose_name="Event Payload",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor User",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="approvals.approval",
                        verbose_name="Approval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Event",
                "verbose_name_plural": "Approval Events",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["approval", "timestamp"],
                        name="idx_events_approval_timestamp",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["status", "created_at"], name="idx_approvals_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["action_type", "created_at"],
                name="idx_approvals_action_created",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["assigned_to_user", "status"],
                name="idx_approvals_assigned_status",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)),
                fields=["expires_at"],
                name="idx_approvals_expires_at",
            ),
        ),
    ]
