# Generated by Django 4.2.26 on 2026-03-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approval",
            options={
                "ordering": ["-created_at"],
                "permissions": [("review", "Can review and act on approvals")],
                "verbose_name": "Approval",
                "verbose_name_plural": "Approvals",
            },
        ),
    ]
