# Generated by Django 4.2.26 on 2026-07-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_alter_approval_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("email", "Send Email"),
                    ("purchase_order", "Create Purchase Order"),
                    ("sales_order", "Create Sales Order"),
                    ("stock_update", "Update Stock"),
                    ("workflow", "Run Workflow"),
                    ("notification", "Send Notification"),
                    ("safety_gate", "Safety Gate"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Action Type",
            ),
        ),
    ]
