# Generated by Django 5.2.15 on 2026-07-12 23:42
"""Approval action-type choice update."""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Widen the approval action-type choices."""


    dependencies = [
        ("approvals", "0003_alter_approval_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approval",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("email", "Send Email"),
                    ("purchase_order", "Create Purchase Order"),
                    ("sales_order", "Create Sales Order"),
                    ("stock_update", "Update Stock"),
                    ("workflow", "Run Workflow"),
                    ("notification", "Send Notification"),
                    ("safety_gate", "Safety Gate"),
                    ("procedure_publish", "Publish Procedure"),
                    ("job_kit_substitution", "Approve Job Kit Substitution"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Action Type",
            ),
        ),
    ]
